import { hashRosterAgent, hashRosterSnapshot, legacyRosterSnapshot, validateRosterAgent, validateRosterSnapshot } from './roster.js';
import type { AgentUsage, RoleProfile, ValidatedWorkflowPassportV2, WorkflowConfig, WorkflowJobV2, WorkflowPassportV2, WorkflowSessionsV2 } from './state.js';
import { WORKFLOW_PHASE_TRANSITIONS, type WorkflowPhase } from './transitions.js';

const PHASES = Object.keys(WORKFLOW_PHASE_TRANSITIONS) as WorkflowPhase[];
const MODES = ['new', 'native_resume', 'passport_handoff', 'none'] as const;

export function validateWorkflowJob(value: unknown): WorkflowJobV2 {
  const raw = record(value, 'workflow job'); if (raw.schema_version === 1) return legacyJob(raw);
  const o = raw; exact(o, ['schema_version', 'job_id', 'mode', 'phase', 'resume_phase', 'revision', 'artifact_revision', 'latest_artifact_hash', 'opus_iteration', 'fix_cycles', 'fable_calls', 'consultation_status', 'consultation_origin', 'branch', 'worktree', 'target_branch', 'base_commit', 'current_commit', 'reviewed_diff_hash', 'accepted_brief_hash', 'last_action', 'blocker', 'next_action', 'current_operation', 'created_at', 'updated_at'], 'workflow job');
  const operation = o.current_operation === null ? null : (() => { const p = record(o.current_operation, 'current_operation'); exact(p, ['phase', 'invocation_id', 'started_at', 'retry_count'], 'current_operation'); return { phase: phase(p.phase), invocation_id: id(p.invocation_id, 'invocation_id'), started_at: timestamp(p.started_at, 'started_at'), retry_count: integer(p.retry_count, 'retry_count', 0) }; })();
  return { schema_version: two(o.schema_version), job_id: id(o.job_id, 'job_id'), mode: enumeration(o.mode, ['adaptive', 'direct'] as const, 'mode'), phase: phase(o.phase), resume_phase: o.resume_phase === null ? null : phase(o.resume_phase), revision: integer(o.revision, 'revision', 1), artifact_revision: integer(o.artifact_revision, 'artifact_revision', 0), latest_artifact_hash: nullableHash(o.latest_artifact_hash, 'latest_artifact_hash'), opus_iteration: integer(o.opus_iteration, 'opus_iteration', 1), fix_cycles: integer(o.fix_cycles, 'fix_cycles', 0), fable_calls: integer(o.fable_calls, 'fable_calls', 0), consultation_status: enumeration(o.consultation_status, ['unused', 'requested', 'attempt_started', 'result_persisted', 'skipped', 'fallback_executed'] as const, 'consultation_status'), consultation_origin: o.consultation_origin === null ? null : enumeration(o.consultation_origin, ['pre_opus', 'post_opus'] as const, 'consultation_origin'), branch: nullableString(o.branch, 'branch'), worktree: nullableString(o.worktree, 'worktree'), target_branch: nullableString(o.target_branch, 'target_branch'), base_commit: nullableString(o.base_commit, 'base_commit'), current_commit: nullableString(o.current_commit, 'current_commit'), reviewed_diff_hash: nullableHash(o.reviewed_diff_hash, 'reviewed_diff_hash'), accepted_brief_hash: nullableHash(o.accepted_brief_hash, 'accepted_brief_hash'), last_action: nullableString(o.last_action, 'last_action'), blocker: nullableString(o.blocker, 'blocker'), next_action: string(o.next_action, 'next_action'), current_operation: operation, created_at: timestamp(o.created_at, 'created_at'), updated_at: timestamp(o.updated_at, 'updated_at') };
}

export function validateWorkflowPassport(value: unknown): ValidatedWorkflowPassportV2 {
  const raw = record(value, 'workflow passport'); if (raw.schema_version === 1) return legacyPassport(raw);
  const o = raw; exactOptional(o, ['schema_version', 'passport_revision', 'job_id', 'mode', 'current_revision', 'objective', 'current_phase', 'accepted_brief_hash', 'latest_implementation_brief', 'hard_constraints', 'acceptance_criteria', 'decisions', 'allowed_file_scope', 'required_checks', 'current_blockers', 'next_action', 'artifacts', 'active_worktree', 'target_branch', 'base_commit', 'current_commit', 'session_references', 'session_modes', 'rotation_history', 'config'], ['roster', 'roster_hash', 'active_roster', 'active_roster_hash', 'roster_revision', 'binding_rotation_history'], 'workflow passport');
  const mode = enumeration(o.mode, ['adaptive', 'direct'] as const, 'mode');
  if (('roster' in o) !== ('roster_hash' in o)) throw new Error('workflow passport roster and roster_hash must be provided together');
  const roster = 'roster' in o ? validateRosterSnapshot(o.roster, mode) : legacyRosterFromConfig(mode, o.config);
  const rosterHash = hashRosterSnapshot(roster);
  if ('roster_hash' in o && hash(o.roster_hash, 'roster_hash') !== rosterHash) throw new Error('workflow passport roster_hash does not match roster');
  const activeFields = ['active_roster', 'active_roster_hash', 'roster_revision', 'binding_rotation_history'] as const;
  const activeCount = activeFields.filter((key) => key in o).length;
  if (activeCount !== 0 && activeCount !== activeFields.length) throw new Error('workflow passport active roster fields must be provided together');
  const activeRoster = activeCount ? validateRosterSnapshot(o.active_roster, mode) : roster;
  const activeRosterHash = hashRosterSnapshot(activeRoster);
  if (activeCount && hash(o.active_roster_hash, 'active_roster_hash') !== activeRosterHash) throw new Error('workflow passport active_roster_hash does not match active_roster');
  const rosterRevision = activeCount ? integer(o.roster_revision, 'roster_revision', 1) : 1;
  const bindingHistory = activeCount ? array(o.binding_rotation_history, 'binding_rotation_history').map((item, index) => bindingRotation(item, `binding_rotation_history[${index}]`)) : [];
  if (bindingHistory.length !== rosterRevision - 1 || bindingHistory.some((item, index) => item.revision !== index + 2)) throw new Error('workflow passport binding rotation history does not match roster_revision');
  return { schema_version: two(o.schema_version), passport_revision: integer(o.passport_revision, 'passport_revision', 1), job_id: id(o.job_id, 'job_id'), mode, current_revision: integer(o.current_revision, 'current_revision', 1), objective: nonEmpty(o.objective, 'objective'), current_phase: phase(o.current_phase), accepted_brief_hash: nullableHash(o.accepted_brief_hash, 'accepted_brief_hash'), latest_implementation_brief: o.latest_implementation_brief === null ? null : artifact(o.latest_implementation_brief, 'latest_implementation_brief'), hard_constraints: strings(o.hard_constraints, 'hard_constraints'), acceptance_criteria: strings(o.acceptance_criteria, 'acceptance_criteria'), decisions: array(o.decisions, 'decisions').map((item, index) => decision(item, `decisions[${index}]`)), allowed_file_scope: strings(o.allowed_file_scope, 'allowed_file_scope'), required_checks: strings(o.required_checks, 'required_checks'), current_blockers: strings(o.current_blockers, 'current_blockers'), next_action: string(o.next_action, 'next_action'), artifacts: array(o.artifacts, 'artifacts').map((item, index) => artifact(item, `artifacts[${index}]`)), active_worktree: nullableString(o.active_worktree, 'active_worktree'), target_branch: nullableString(o.target_branch, 'target_branch'), base_commit: nullableString(o.base_commit, 'base_commit'), current_commit: nullableString(o.current_commit, 'current_commit'), session_references: duo(o.session_references, nullableString), session_modes: duo(o.session_modes, sessionMode), rotation_history: array(o.rotation_history, 'rotation_history').map((item, index) => rotation(item, `rotation_history[${index}]`)), config: config(o.config), roster, roster_hash: rosterHash, active_roster: activeRoster, active_roster_hash: activeRosterHash, roster_revision: rosterRevision, binding_rotation_history: bindingHistory };
}

export function validateWorkflowSessions(value: unknown): WorkflowSessionsV2 {
  const raw = record(value, 'workflow sessions'); if (raw.schema_version === 1) return legacySessions(raw);
  const o = raw; exact(o, ['schema_version', 'sessions_revision', 'job_id', 'codex_thread_id', 'opus_session_id', 'opus_brief_hash', 'modes', 'rotation_history', 'recorded_invocations', 'usage', 'updated_at'], 'workflow sessions');
  return { schema_version: two(o.schema_version), sessions_revision: integer(o.sessions_revision, 'sessions_revision', 1), job_id: id(o.job_id, 'job_id'), codex_thread_id: nullableString(o.codex_thread_id, 'codex_thread_id'), opus_session_id: nullableString(o.opus_session_id, 'opus_session_id'), opus_brief_hash: nullableHash(o.opus_brief_hash, 'opus_brief_hash'), modes: duo(o.modes, sessionMode), rotation_history: array(o.rotation_history, 'rotation_history').map((item, index) => rotation(item, `rotation_history[${index}]`)), recorded_invocations: strings(o.recorded_invocations, 'recorded_invocations').map((item) => id(item, 'invocation_id')), usage: trio(o.usage, usage), updated_at: timestamp(o.updated_at, 'updated_at') };
}

function config(value: unknown): WorkflowConfig { const o = record(value, 'workflow config'); exact(o, ['fable_total_cap', 'max_input_bytes', 'max_output_bytes', 'passport_max_bytes', 'profiles'], 'workflow config'); return { fable_total_cap: enumeration(o.fable_total_cap, [0, 1] as const, 'fable_total_cap'), max_input_bytes: integer(o.max_input_bytes, 'max_input_bytes', 1), max_output_bytes: integer(o.max_output_bytes, 'max_output_bytes', 1), passport_max_bytes: integer(o.passport_max_bytes, 'passport_max_bytes', 1), profiles: trio(o.profiles, profile) }; }
function profile(value: unknown, label: string): RoleProfile { const o = record(value, label); exact(o, ['model', 'effort', 'max_turns', 'timeout_ms', 'permission_mode'], label); return { model: model(o.model, `${label}.model`), effort: enumeration(o.effort, ['low', 'medium', 'high'] as const, `${label}.effort`), max_turns: integer(o.max_turns, `${label}.max_turns`, 1), timeout_ms: integer(o.timeout_ms, `${label}.timeout_ms`, 1), permission_mode: enumeration(o.permission_mode, ['read_only', 'worktree'] as const, `${label}.permission_mode`) }; }
function artifact(value: unknown, label: string): WorkflowPassportV2['artifacts'][number] { const o = record(value, label); exact(o, ['filename', 'hash', 'phase', 'revision', 'iteration', 'role'], label); const filename = nonEmpty(o.filename, `${label}.filename`); if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(filename)) throw new Error(`${label}.filename is invalid`); return { filename, hash: hash(o.hash, `${label}.hash`), phase: phase(o.phase), revision: integer(o.revision, `${label}.revision`, 1), iteration: integer(o.iteration, `${label}.iteration`, 1), role: enumeration(o.role, ['codex', 'fable', 'opus', 'orchestrator', 'human'] as const, `${label}.role`) }; }
function decision(value: unknown, label: string): WorkflowPassportV2['decisions'][number] { const o = record(value, label); exact(o, ['invocation_id', 'action', 'summary', 'provenance', 'timestamp', 'fable_advice_disposition', 'fable_error', 'fable_iteration_effect'], label); return { invocation_id: id(o.invocation_id, `${label}.invocation_id`), action: nonEmpty(o.action, `${label}.action`), summary: nonEmpty(o.summary, `${label}.summary`), provenance: enumeration(o.provenance, ['codex'] as const, `${label}.provenance`), timestamp: timestamp(o.timestamp, `${label}.timestamp`), fable_advice_disposition: o.fable_advice_disposition === null ? null : enumeration(o.fable_advice_disposition, ['accepted', 'rejected'] as const, `${label}.fable_advice_disposition`), fable_error: nullableString(o.fable_error, `${label}.fable_error`), fable_iteration_effect: o.fable_iteration_effect === null ? null : enumeration(o.fable_iteration_effect, ['avoided', 'added', 'unchanged'] as const, `${label}.fable_iteration_effect`) }; }
function rotation(value: unknown, label: string): WorkflowSessionsV2['rotation_history'][number] { const o = record(value, label); exact(o, ['role', 'previous_id', 'next_id', 'reason', 'timestamp'], label); return { role: enumeration(o.role, ['codex', 'opus'] as const, `${label}.role`), previous_id: nullableString(o.previous_id, `${label}.previous_id`), next_id: nullableString(o.next_id, `${label}.next_id`), reason: nonEmpty(o.reason, `${label}.reason`), timestamp: timestamp(o.timestamp, `${label}.timestamp`) }; }
function bindingRotation(value: unknown, label: string): ValidatedWorkflowPassportV2['binding_rotation_history'][number] { const o = record(value, label); exact(o, ['role', 'previous_binding_hash', 'new_binding_hash', 'previous_binding', 'new_binding', 'reason', 'timestamp', 'revision'], label); const previous = o.previous_binding === null ? null : validateRosterAgent(o.previous_binding, `${label}.previous_binding`); const next = o.new_binding === null ? null : validateRosterAgent(o.new_binding, `${label}.new_binding`); const previousHash = nullableHash(o.previous_binding_hash, `${label}.previous_binding_hash`); const newHash = nullableHash(o.new_binding_hash, `${label}.new_binding_hash`); if ((previous ? hashRosterAgent(previous) : null) !== previousHash || (next ? hashRosterAgent(next) : null) !== newHash) throw new Error(`${label} binding hash does not match binding`); return { role: enumeration(o.role, ['supervisor', 'implementer', 'adviser', 'reviewer'] as const, `${label}.role`), previous_binding_hash: previousHash, new_binding_hash: newHash, previous_binding: previous, new_binding: next, reason: nonEmpty(o.reason, `${label}.reason`), timestamp: timestamp(o.timestamp, `${label}.timestamp`), revision: integer(o.revision, `${label}.revision`, 2) }; }
function usage(value: unknown, label: string): AgentUsage { const o = record(value, label); exact(o, ['calls', 'input_chars', 'output_chars', 'input_tokens', 'output_tokens', 'estimated_tokens', 'cache_read', 'cache_write', 'duration_ms', 'failed_calls', 'resumes', 'compactions'], label); return Object.fromEntries(Object.keys(o).map((key) => [key, integer(o[key], `${label}.${key}`, 0)])) as unknown as AgentUsage; }
function duo<T>(value: unknown, validate: (value: unknown, label: string) => T): Record<'codex' | 'opus', T> { const o = record(value, 'role record'); exact(o, ['codex', 'opus'], 'role record'); return { codex: validate(o.codex, 'codex'), opus: validate(o.opus, 'opus') }; }
function trio<T>(value: unknown, validate: (value: unknown, label: string) => T): Record<'codex' | 'fable' | 'opus', T> { const o = record(value, 'role record'); exact(o, ['codex', 'fable', 'opus'], 'role record'); return { codex: validate(o.codex, 'codex'), fable: validate(o.fable, 'fable'), opus: validate(o.opus, 'opus') }; }
function sessionMode(value: unknown, label: string) { return enumeration(value, MODES, label); }
function phase(value: unknown): WorkflowPhase { return enumeration(value, PHASES, 'phase'); }
function record(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, keys: string[], label: string) { const expected = new Set(keys); for (const key of keys) if (!(key in value)) throw new Error(`${label} is missing ${key}`); for (const key of Object.keys(value)) if (!expected.has(key)) throw new Error(`${label} contains unknown field ${key}`); }
function exactOptional(value: Record<string, unknown>, required: string[], optional: string[], label: string) { const expected = new Set([...required, ...optional]); for (const key of required) if (!(key in value)) throw new Error(`${label} is missing ${key}`); for (const key of Object.keys(value)) if (!expected.has(key)) throw new Error(`${label} contains unknown field ${key}`); }
function array(value: unknown, label: string): unknown[] { if (!Array.isArray(value)) throw new Error(`${label} must be an array`); return value; }
function strings(value: unknown, label: string): string[] { return array(value, label).map((item, index) => string(item, `${label}[${index}]`)); }
function string(value: unknown, label: string): string { if (typeof value !== 'string') throw new Error(`${label} must be a string`); return value; }
function nonEmpty(value: unknown, label: string): string { const result = string(value, label); if (!result.trim()) throw new Error(`${label} must not be empty`); return result; }
function model(value: unknown, label: string): string { const result = string(value, label); if (result === '') return result; if (!/^[A-Za-z0-9][A-Za-z0-9._/-]{0,127}$/.test(result)) throw new Error(`${label} is invalid`); return result; }
function nullableString(value: unknown, label: string): string | null { return value === null ? null : string(value, label); }
function hash(value: unknown, label: string): string { const result = string(value, label); if (!/^[a-f0-9]{64}$/.test(result)) throw new Error(`${label} must be a SHA-256 hash`); return result; }
function nullableHash(value: unknown, label: string): string | null { return value === null ? null : hash(value, label); }
function integer(value: unknown, label: string, minimum: number): number { if (!Number.isSafeInteger(value) || (value as number) < minimum) throw new Error(`${label} must be an integer >= ${minimum}`); return value as number; }
function timestamp(value: unknown, label: string): string { const result = string(value, label); if (!Number.isFinite(Date.parse(result))) throw new Error(`${label} must be a timestamp`); return result; }
function id(value: unknown, label: string): string { const result = nonEmpty(value, label); if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(result)) throw new Error(`${label} is invalid`); return result; }
function two(value: unknown): 2 { if (value !== 2) throw new Error('Unsupported workflow schema version'); return 2; }
function enumeration<const T extends readonly (string | number)[]>(value: unknown, allowed: T, label: string): T[number] { if (!allowed.includes(value as never)) throw new Error(`${label} has an invalid value`); return value as T[number]; }

function legacyJob(o: Record<string, unknown>): WorkflowJobV2 { const terminal = o.phase === 'done' || o.phase === 'cancelled' || o.phase === 'failed' ? o.phase as 'done' | 'cancelled' | 'failed' : 'blocked'; const now = typeof o.updated_at === 'string' ? o.updated_at : new Date(0).toISOString(); return { schema_version: 2, job_id: id(o.job_id, 'job_id'), mode: 'adaptive', phase: terminal, resume_phase: null, revision: Number(o.revision) || 1, artifact_revision: Number(o.artifact_revision) || 0, latest_artifact_hash: typeof o.latest_artifact_hash === 'string' ? o.latest_artifact_hash : null, opus_iteration: Number(o.opus_iteration) || 1, fix_cycles: Number(o.fix_cycles) || 0, fable_calls: Number(o.fable_total_calls) || 0, consultation_status: 'skipped', consultation_origin: null, branch: stringOrNull(o.branch), worktree: stringOrNull(o.worktree), target_branch: stringOrNull(o.target_branch), base_commit: stringOrNull(o.base_commit), current_commit: stringOrNull(o.current_commit), reviewed_diff_hash: stringOrNull(o.reviewed_diff_hash), accepted_brief_hash: null, last_action: null, blocker: terminal === 'blocked' ? 'LEGACY_SCHEMA: start a new workflow; v1 execution cannot be resumed safely' : stringOrNull(o.blocker), next_action: terminal === 'blocked' ? 'Start a new adaptive or direct workflow' : String(o.next_action ?? 'No further action'), current_operation: null, created_at: typeof o.created_at === 'string' ? o.created_at : now, updated_at: now }; }
function legacyPassport(o: Record<string, unknown>): ValidatedWorkflowPassportV2 { const jobId = id(o.job_id, 'job_id'); const roster = legacyRosterSnapshot('adaptive'); const rosterHash = hashRosterSnapshot(roster); return { schema_version: 2, passport_revision: Number(o.passport_revision) || 1, job_id: jobId, mode: 'adaptive', current_revision: Number(o.current_revision) || 1, objective: String(o.objective ?? 'Legacy workflow'), current_phase: 'blocked', accepted_brief_hash: null, latest_implementation_brief: null, hard_constraints: Array.isArray(o.hard_constraints) ? o.hard_constraints.map(String) : [], acceptance_criteria: Array.isArray(o.acceptance_criteria) ? o.acceptance_criteria.map(String) : [], decisions: [], allowed_file_scope: Array.isArray(o.allowed_file_scope) ? o.allowed_file_scope.map(String) : [], required_checks: Array.isArray(o.required_checks) ? o.required_checks.map(String) : [], current_blockers: ['LEGACY_SCHEMA: v1 workflow is inspectable but not resumable'], next_action: 'Start a new workflow', artifacts: [], active_worktree: stringOrNull(o.active_worktree), target_branch: stringOrNull(o.target_branch), base_commit: stringOrNull(o.base_commit), current_commit: stringOrNull(o.current_commit), session_references: { codex: null, opus: null }, session_modes: { codex: 'none', opus: 'none' }, rotation_history: [], config: legacyConfig(o.config), roster, roster_hash: rosterHash, active_roster: roster, active_roster_hash: rosterHash, roster_revision: 1, binding_rotation_history: [] }; }
function legacySessions(o: Record<string, unknown>): WorkflowSessionsV2 { const empty = zeroUsage(); const oldUsage = o.usage && typeof o.usage === 'object' ? o.usage as Record<string, AgentUsage> : {}; return { schema_version: 2, sessions_revision: 1, job_id: id(o.job_id, 'job_id'), codex_thread_id: stringOrNull(o.codex_thread_id), opus_session_id: stringOrNull(o.opus_session_id), opus_brief_hash: null, modes: { codex: 'none', opus: 'none' }, rotation_history: [], recorded_invocations: Array.isArray(o.recorded_invocations) ? o.recorded_invocations.map(String) : [], usage: { codex: oldUsage.codex ?? empty, fable: oldUsage.fable ?? empty, opus: oldUsage.opus ?? empty }, updated_at: typeof o.updated_at === 'string' ? o.updated_at : new Date(0).toISOString() }; }
function legacyConfig(value: unknown): WorkflowConfig { const o = value && typeof value === 'object' ? value as Record<string, unknown> : {}; const defaults = { fable: { model: 'fable', effort: 'low', max_turns: 1, timeout_ms: 300000, permission_mode: 'read_only' }, opus: { model: 'opus', effort: 'high', max_turns: 50, timeout_ms: 1800000, permission_mode: 'worktree' }, codex: { model: 'codex', effort: 'medium', max_turns: 1, timeout_ms: 600000, permission_mode: 'read_only' } } as WorkflowConfig['profiles']; return { fable_total_cap: 1, max_input_bytes: Number(o.max_input_bytes) || 128000, max_output_bytes: Number(o.max_output_bytes) || 64000, passport_max_bytes: Number(o.passport_max_bytes) || 64000, profiles: o.profiles && typeof o.profiles === 'object' ? o.profiles as WorkflowConfig['profiles'] : defaults }; }
function legacyRosterFromConfig(mode: 'adaptive' | 'direct', value: unknown) { const c = config(value); const binding = (adapter: string, name: 'codex' | 'opus' | 'fable') => ({ adapter, profile: { name, model: c.profiles[name].model, effort: c.profiles[name].effort, max_turns: c.profiles[name].max_turns, timeout_ms: c.profiles[name].timeout_ms } }); return validateRosterSnapshot({ schema_version: 1, supervisor: binding('codex', 'codex'), implementer: binding('claude', 'opus'), adviser: mode === 'adaptive' && c.fable_total_cap > 0 ? binding('fable', 'fable') : null, reviewer: { same_as: 'supervisor' } }, mode); }
function zeroUsage(): AgentUsage { return { calls: 0, input_chars: 0, output_chars: 0, input_tokens: 0, output_tokens: 0, estimated_tokens: 0, cache_read: 0, cache_write: 0, duration_ms: 0, failed_calls: 0, resumes: 0, compactions: 0 }; }
function stringOrNull(value: unknown): string | null { return typeof value === 'string' ? value : null; }
