import type { AgentUsage, RoleProfile, WorkflowConfig, WorkflowJobV1, WorkflowPassportV1, WorkflowSessionsV1 } from './state.js';
import { WORKFLOW_PHASE_TRANSITIONS, type WorkflowPhase } from './transitions.js';

const PHASES = Object.keys(WORKFLOW_PHASE_TRANSITIONS) as WorkflowPhase[];
const MODES = ['new', 'native_resume', 'passport_handoff', 'none'] as const;
const ROLES = ['codex', 'fable', 'opus'] as const;

export function validateWorkflowJob(value: unknown): WorkflowJobV1 {
  const o = record(upgradeJob(value), 'workflow job');
  exact(o, ['schema_version', 'job_id', 'phase', 'resume_phase', 'revision', 'artifact_revision', 'latest_artifact_hash', 'fable_pre_opus_calls', 'fable_post_opus_calls', 'fable_post_opus_iteration_calls', 'fable_total_calls', 'fix_cycles', 'opus_iteration', 'branch', 'worktree', 'target_branch', 'base_commit', 'current_commit', 'approved_plan_hash', 'reviewed_diff_hash', 'last_verdict', 'blocker', 'next_action', 'current_operation', 'created_at', 'updated_at'], 'workflow job');
  const operation = o.current_operation === null ? null : (() => { const p = record(o.current_operation, 'current_operation'); exact(p, ['phase', 'invocation_id', 'started_at', 'retry_count'], 'current_operation'); return { phase: phase(p.phase), invocation_id: id(p.invocation_id, 'invocation_id'), started_at: timestamp(p.started_at, 'started_at'), retry_count: integer(p.retry_count, 'retry_count', 0) }; })();
  return { schema_version: one(o.schema_version), job_id: id(o.job_id, 'job_id'), phase: phase(o.phase), resume_phase: o.resume_phase === null ? null : phase(o.resume_phase), revision: integer(o.revision, 'revision', 1), artifact_revision: integer(o.artifact_revision, 'artifact_revision', 0), latest_artifact_hash: nullableHash(o.latest_artifact_hash, 'latest_artifact_hash'), fable_pre_opus_calls: integer(o.fable_pre_opus_calls, 'fable_pre_opus_calls', 0), fable_post_opus_calls: integer(o.fable_post_opus_calls, 'fable_post_opus_calls', 0), fable_post_opus_iteration_calls: integer(o.fable_post_opus_iteration_calls, 'fable_post_opus_iteration_calls', 0), fable_total_calls: integer(o.fable_total_calls, 'fable_total_calls', 0), fix_cycles: integer(o.fix_cycles, 'fix_cycles', 0), opus_iteration: integer(o.opus_iteration, 'opus_iteration', 1), branch: nullableString(o.branch, 'branch'), worktree: nullableString(o.worktree, 'worktree'), target_branch: nullableString(o.target_branch, 'target_branch'), base_commit: nullableString(o.base_commit, 'base_commit'), current_commit: nullableString(o.current_commit, 'current_commit'), approved_plan_hash: nullableHash(o.approved_plan_hash, 'approved_plan_hash'), reviewed_diff_hash: nullableHash(o.reviewed_diff_hash, 'reviewed_diff_hash'), last_verdict: nullableString(o.last_verdict, 'last_verdict'), blocker: nullableString(o.blocker, 'blocker'), next_action: string(o.next_action, 'next_action'), current_operation: operation, created_at: timestamp(o.created_at, 'created_at'), updated_at: timestamp(o.updated_at, 'updated_at') };
}

export function validateWorkflowPassport(value: unknown): WorkflowPassportV1 {
  const o = record(upgradePassport(value), 'workflow passport');
  exact(o, ['schema_version', 'passport_revision', 'job_id', 'current_revision', 'objective', 'current_phase', 'approved_plan_hash', 'latest_accepted_plan', 'hard_constraints', 'acceptance_criteria', 'mandatory_amendments', 'decisions', 'allowed_file_scope', 'required_checks', 'current_blockers', 'next_action', 'artifacts', 'active_worktree', 'target_branch', 'base_commit', 'current_commit', 'session_references', 'session_modes', 'rotation_history', 'config'], 'workflow passport');
  return { schema_version: one(o.schema_version), passport_revision: integer(o.passport_revision, 'passport_revision', 1), job_id: id(o.job_id, 'job_id'), current_revision: integer(o.current_revision, 'current_revision', 1), objective: nonEmpty(o.objective, 'objective'), current_phase: phase(o.current_phase), approved_plan_hash: nullableHash(o.approved_plan_hash, 'approved_plan_hash'), latest_accepted_plan: o.latest_accepted_plan === null ? null : artifact(o.latest_accepted_plan, 'latest_accepted_plan'), hard_constraints: strings(o.hard_constraints, 'hard_constraints'), acceptance_criteria: strings(o.acceptance_criteria, 'acceptance_criteria'), mandatory_amendments: strings(o.mandatory_amendments, 'mandatory_amendments'), decisions: array(o.decisions, 'decisions').map((item, index) => decision(item, `decisions[${index}]`)), allowed_file_scope: strings(o.allowed_file_scope, 'allowed_file_scope'), required_checks: strings(o.required_checks, 'required_checks'), current_blockers: strings(o.current_blockers, 'current_blockers'), next_action: string(o.next_action, 'next_action'), artifacts: array(o.artifacts, 'artifacts').map((item, index) => artifact(item, `artifacts[${index}]`)), active_worktree: nullableString(o.active_worktree, 'active_worktree'), target_branch: nullableString(o.target_branch, 'target_branch'), base_commit: nullableString(o.base_commit, 'base_commit'), current_commit: nullableString(o.current_commit, 'current_commit'), session_references: roleRecord(o.session_references, nullableString), session_modes: roleRecord(o.session_modes, mode), rotation_history: array(o.rotation_history, 'rotation_history').map((item, index) => rotation(item, `rotation_history[${index}]`)), config: config(o.config) };
}

export function validateWorkflowSessions(value: unknown): WorkflowSessionsV1 {
  const o = record(upgradeSessions(value), 'workflow sessions');
  exact(o, ['schema_version', 'job_id', 'codex_thread_id', 'fable_session_id', 'opus_session_id', 'opus_plan_hash', 'modes', 'rotation_history', 'recorded_invocations', 'usage', 'updated_at'], 'workflow sessions');
  return { schema_version: one(o.schema_version), job_id: id(o.job_id, 'job_id'), codex_thread_id: nullableString(o.codex_thread_id, 'codex_thread_id'), fable_session_id: nullableString(o.fable_session_id, 'fable_session_id'), opus_session_id: nullableString(o.opus_session_id, 'opus_session_id'), opus_plan_hash: nullableHash(o.opus_plan_hash, 'opus_plan_hash'), modes: roleRecord(o.modes, mode), rotation_history: array(o.rotation_history, 'rotation_history').map((item, index) => rotation(item, `rotation_history[${index}]`)), recorded_invocations: strings(o.recorded_invocations, 'recorded_invocations').map((item) => id(item, 'invocation_id')), usage: roleRecord(o.usage, usage), updated_at: timestamp(o.updated_at, 'updated_at') };
}

function config(value: unknown): WorkflowConfig { const o = record(value, 'workflow config'); exact(o, ['fable_pre_opus_cap', 'fable_post_opus_per_iteration_cap', 'fable_total_cap', 'max_input_bytes', 'max_output_bytes', 'passport_max_bytes', 'post_review', 'profiles'], 'workflow config'); const profiles = roleRecord(o.profiles, profile); return { fable_pre_opus_cap: integer(o.fable_pre_opus_cap, 'fable_pre_opus_cap', 1), fable_post_opus_per_iteration_cap: integer(o.fable_post_opus_per_iteration_cap, 'fable_post_opus_per_iteration_cap', 0), fable_total_cap: integer(o.fable_total_cap, 'fable_total_cap', 1), max_input_bytes: integer(o.max_input_bytes, 'max_input_bytes', 1), max_output_bytes: integer(o.max_output_bytes, 'max_output_bytes', 1), passport_max_bytes: integer(o.passport_max_bytes, 'passport_max_bytes', 1), post_review: enumeration(o.post_review, ['always'] as const, 'post_review'), profiles }; }
function profile(value: unknown, label: string): RoleProfile { const o = record(value, label); exact(o, ['model', 'effort', 'max_turns', 'timeout_ms', 'permission_mode'], label); return { model: nonEmpty(o.model, `${label}.model`), effort: enumeration(o.effort, ['low', 'medium', 'high'] as const, `${label}.effort`), max_turns: integer(o.max_turns, `${label}.max_turns`, 1), timeout_ms: integer(o.timeout_ms, `${label}.timeout_ms`, 1), permission_mode: enumeration(o.permission_mode, ['read_only', 'worktree'] as const, `${label}.permission_mode`) }; }
function artifact(value: unknown, label: string): WorkflowPassportV1['artifacts'][number] { const o = record(value, label); exact(o, ['filename', 'hash', 'phase', 'revision', 'iteration', 'role'], label); const filename = nonEmpty(o.filename, `${label}.filename`); if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(filename)) throw new Error(`${label}.filename is invalid`); return { filename, hash: hash(o.hash, `${label}.hash`), phase: phase(o.phase), revision: integer(o.revision, `${label}.revision`, 1), iteration: integer(o.iteration, `${label}.iteration`, 1), role: enumeration(o.role, ['codex', 'fable', 'opus', 'orchestrator'] as const, `${label}.role`) }; }
function decision(value: unknown, label: string): WorkflowPassportV1['decisions'][number] { const o = record(value, label); exact(o, ['invocation_id', 'verdict', 'reason', 'timestamp'], label); return { invocation_id: id(o.invocation_id, `${label}.invocation_id`), verdict: nonEmpty(o.verdict, `${label}.verdict`), reason: nonEmpty(o.reason, `${label}.reason`), timestamp: timestamp(o.timestamp, `${label}.timestamp`) }; }
function rotation(value: unknown, label: string): WorkflowSessionsV1['rotation_history'][number] { const o = record(value, label); exact(o, ['role', 'previous_id', 'next_id', 'reason', 'timestamp'], label); return { role: enumeration(o.role, ROLES, `${label}.role`), previous_id: nullableString(o.previous_id, `${label}.previous_id`), next_id: nullableString(o.next_id, `${label}.next_id`), reason: nonEmpty(o.reason, `${label}.reason`), timestamp: timestamp(o.timestamp, `${label}.timestamp`) }; }
function usage(value: unknown, label: string): AgentUsage { const o = record(value, label); exact(o, ['calls', 'input_chars', 'output_chars', 'input_tokens', 'output_tokens', 'estimated_tokens', 'cache_read', 'cache_write', 'duration_ms', 'failed_calls', 'resumes', 'compactions'], label); return Object.fromEntries(Object.keys(o).map((key) => [key, integer(o[key], `${label}.${key}`, 0)])) as unknown as AgentUsage; }
function roleRecord<T>(value: unknown, validate: (value: unknown, label: string) => T): Record<'codex' | 'fable' | 'opus', T> { const o = record(value, 'role record'); exact(o, [...ROLES], 'role record'); return { codex: validate(o.codex, 'codex'), fable: validate(o.fable, 'fable'), opus: validate(o.opus, 'opus') }; }
function mode(value: unknown, label: string) { return enumeration(value, MODES, label); }
function phase(value: unknown): WorkflowPhase { return enumeration(value, PHASES, 'phase'); }
function record(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, keys: string[], label: string) { const expected = new Set(keys); for (const key of keys) if (!(key in value)) throw new Error(`${label} is missing ${key}`); for (const key of Object.keys(value)) if (!expected.has(key)) throw new Error(`${label} contains unknown field ${key}`); }
function array(value: unknown, label: string): unknown[] { if (!Array.isArray(value)) throw new Error(`${label} must be an array`); return value; }
function strings(value: unknown, label: string): string[] { return array(value, label).map((item, index) => string(item, `${label}[${index}]`)); }
function string(value: unknown, label: string): string { if (typeof value !== 'string') throw new Error(`${label} must be a string`); return value; }
function nonEmpty(value: unknown, label: string): string { const result = string(value, label); if (!result.trim()) throw new Error(`${label} must not be empty`); return result; }
function nullableString(value: unknown, label: string): string | null { return value === null ? null : string(value, label); }
function hash(value: unknown, label: string): string { const result = string(value, label); if (!/^[a-f0-9]{64}$/.test(result)) throw new Error(`${label} must be a SHA-256 hash`); return result; }
function nullableHash(value: unknown, label: string): string | null { return value === null ? null : hash(value, label); }
function integer(value: unknown, label: string, minimum: number): number { if (!Number.isSafeInteger(value) || (value as number) < minimum) throw new Error(`${label} must be an integer >= ${minimum}`); return value as number; }
function timestamp(value: unknown, label: string): string { const result = string(value, label); if (!Number.isFinite(Date.parse(result))) throw new Error(`${label} must be a timestamp`); return result; }
function id(value: unknown, label: string): string { const result = nonEmpty(value, label); if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(result)) throw new Error(`${label} is invalid`); return result; }
function one(value: unknown): 1 { if (value !== 1) throw new Error('Unsupported workflow schema version'); return 1; }
function enumeration<const T extends readonly string[]>(value: unknown, allowed: T, label: string): T[number] { if (typeof value !== 'string' || !allowed.includes(value)) throw new Error(`${label} has an invalid value`); return value as T[number]; }

function upgradeJob(value: unknown): unknown { const o = record(value, 'workflow job'); if (o.schema_version !== 1) return value; const operation = o.current_operation && typeof o.current_operation === 'object' && !Array.isArray(o.current_operation) ? { ...(o.current_operation as Record<string, unknown>), retry_count: (o.current_operation as Record<string, unknown>).retry_count ?? 0 } : o.current_operation; return { ...o, target_branch: o.target_branch ?? null, base_commit: o.base_commit ?? null, reviewed_diff_hash: o.reviewed_diff_hash ?? null, current_operation: operation }; }
function upgradePassport(value: unknown): unknown { const o = record(value, 'workflow passport'); if (o.schema_version !== 1) return value; const rawConfig = record(o.config, 'workflow config'); const { risk_triggers: _obsolete, ...configFields } = rawConfig; const artifacts = Array.isArray(o.artifacts) ? o.artifacts.map((item) => { const a = record(item, 'artifact'); const filename = typeof a.filename === 'string' ? a.filename : ''; return { ...a, iteration: a.iteration ?? 1, role: a.role ?? roleForLegacyArtifact(filename) }; }) : o.artifacts; const decisions = Array.isArray(o.decisions) ? o.decisions.map((item, index) => ({ ...record(item, 'decision'), invocation_id: record(item, 'decision').invocation_id ?? `legacy_decision_${index + 1}` })) : o.decisions; return { ...o, latest_accepted_plan: o.latest_accepted_plan ?? null, hard_constraints: o.hard_constraints ?? [], target_branch: o.target_branch ?? null, base_commit: o.base_commit ?? null, artifacts, decisions, config: { ...configFields, post_review: 'always' } }; }
function upgradeSessions(value: unknown): unknown { const o = record(value, 'workflow sessions'); if (o.schema_version !== 1) return value; return { ...o, recorded_invocations: o.recorded_invocations ?? [] }; }
function roleForLegacyArtifact(filename: string): 'codex' | 'fable' | 'opus' | 'orchestrator' { if (filename.startsWith('codex-')) return 'codex'; if (filename.startsWith('fable-')) return 'fable'; if (filename.startsWith('opus-report')) return 'opus'; return 'orchestrator'; }
