import { execFile } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
import type { CheckResults, CodexBrief, CodexPlanReview, CodexSynthesis, CodexTechnicalReview, FableComplianceReview, FablePlan, OpusResult } from '../../domain/workflow/contracts.js';
import type { WorkflowPassportV1 } from '../../domain/workflow/state.js';
import type { IProcessManager } from '../process/process-manager.js';
import { buildChildEnv } from '../adapters/utils.js';
import type { CodexRolePort, FableCallOptions, FableRolePort, GitEvidence, OpusRolePort, RoleResult, WorkflowGitPort } from '../../application/workflow/ports.js';
import { hashCanonical } from './artifact-store.js';

const execFileAsync = promisify(execFile);

export class NativeCodexWorkflowAdapter implements CodexRolePort {
  constructor(private readonly pm: IProcessManager) {}
  brief(passport: WorkflowPassportV1, thread: string | null) { return this.call<CodexBrief>('Create a concise implementation brief as strict JSON with job_id, objective, constraints, allowed_file_scope, required_checks.', passport, thread); }
  reviewPlan(passport: WorkflowPassportV1, plan: FablePlan, thread: string | null) { return this.call<CodexPlanReview>('Review this plan. Return only strict JSON with job_id, revision, verdict GO|APPLY_AND_GO|REVISE|STOP, summary, required_changes, requires_re_review, risk_level low|medium|high, reason, acceptance_criteria. APPLY_AND_GO is only for bounded changes.', { passport: project(passport), plan }, thread); }
  compileFinalPrompt(passport: WorkflowPassportV1, plan: unknown, thread: string | null) { return this.callText('Compile a concise executable Opus prompt from the approved passport and plan. Output prompt text only.', { passport, plan }, thread); }
  technicalReview(passport: WorkflowPassportV1, evidence: GitEvidence, checks: CheckResults, thread: string | null) { return this.call<CodexTechnicalReview>('Inspect the files in the current worktree plus the actual diff and checks as primary evidence. Return only strict JSON with job_id, reviewed_commit, checks_passed, evidence, required_fixes, concise_reason.', { passport, evidence, checks }, thread, evidence.worktree); }
  synthesize(passport: WorkflowPassportV1, evidence: GitEvidence, technical: CodexTechnicalReview, compliance: FableComplianceReview | null, checks: CheckResults, thread: string | null) { return this.call<CodexSynthesis>('Return only strict JSON with job_id, reviewed_commit, verdict GO|REVISE|STOP, merge_allowed, evidence, summary, required_changes, requires_re_review, risk_level low|medium|high, reason. GO requires passing meaningful checks and no required changes.', { passport: project(passport), evidence, technical, compliance, checks }, thread, evidence.worktree); }
  async available() { return availability('codex'); }
  private async call<T>(instruction: string, projection: unknown, thread: string | null, cwd = process.cwd()): Promise<RoleResult<T>> { const result = await this.run(instruction, projection, cwd); return { value: parseJson<T>(result.text), session_id: result.sessionId ?? thread ?? undefined, resumed: false, resume_failed: thread !== null, usage: result.usage }; }
  private async callText(instruction: string, projection: unknown, thread: string | null): Promise<RoleResult<string>> { const result = await this.run(instruction, projection, process.cwd()); return { value: result.text, session_id: result.sessionId ?? thread ?? undefined, resumed: false, resume_failed: thread !== null, usage: result.usage }; }
  private async run(instruction: string, projection: unknown, cwd: string) { const prompt = bounded(`${instruction}\n\n${JSON.stringify(projection)}`, 256_000); const output = await spawnCapture(this.pm, 'codex', ['exec', '--json', '--sandbox', 'read-only', '-'], cwd, prompt, 1_000_000, 600_000); const lines = output.split('\n').filter(Boolean).map(parseObject); let text = ''; let sessionId: string | undefined; let usage: Record<string, number> = {}; for (const line of lines) { if (line.type === 'thread.started' && typeof line.thread_id === 'string') sessionId = line.thread_id; const item = object(line.item); if (item.type === 'agent_message' && typeof item.text === 'string') text = item.text; if (line.type === 'turn.completed') usage = usageObject(line.usage); } if (!text) throw new Error('Codex returned no agent message'); return { text, sessionId, usage: { input_chars: prompt.length, output_chars: text.length, input_tokens: usage.input_tokens, output_tokens: usage.output_tokens } }; }
}

export class NativeFableWorkflowAdapter implements FableRolePort {
  constructor(private readonly pm: IProcessManager) {}
  plan(passport: WorkflowPassportV1, brief: CodexBrief, previous: FablePlan | null, changes: string[], options: FableCallOptions) { return this.call<FablePlan>('Produce only strict JSON: job_id, revision, assumptions, acceptance_criteria, implementation_steps, risks, questions_requiring_human.', { passport, brief, previous, changes }, options, true); }
  finalPrompt(passport: WorkflowPassportV1, plan: FablePlan, amendments: string[], options: FableCallOptions) { return this.call<string>('Apply bounded amendments and output only the final implementation prompt.', { passport, plan, amendments }, options, false); }
  compliance(passport: WorkflowPassportV1, plan: FablePlan, opus: OpusResult, evidence: GitEvidence, checks: CheckResults, options: FableCallOptions) { return this.call<FableComplianceReview>('Evaluate plan compliance from the actual diff and checks. Output only strict JSON: job_id, approved_plan_hash, verdict ALIGNED|GAPS_FOUND|UNCERTAIN, plan_deviations, missing_requirements, recommended_repairs.', { passport: project(passport), plan, opus, evidence, checks }, options, true); }
  async available() { return availability('claude'); }
  private async call<T>(instruction: string, projection: unknown, options: FableCallOptions, json: boolean): Promise<RoleResult<T>> { const prompt = bounded(`${instruction}\n\n${JSON.stringify(projection)}`, options.max_input_bytes); const result = await claudeCall(this.pm, prompt, options.workspace, options.model, 1, 'low', options.timeout_ms, options.max_output_bytes, true); return { value: (json ? parseJson(result.text) : result.text) as T, session_id: result.sessionId, session_mode: 'none', usage: result.usage }; }
}

export class NativeOpusWorkflowAdapter implements OpusRolePort {
  constructor(private readonly pm: IProcessManager) {}
  async execute(passport: WorkflowPassportV1, prompt: string, workspace: string, sessionId: string | null, mode: 'new' | 'native_resume' | 'passport_handoff') {
    const taskContext = JSON.stringify({
      job_id: passport.job_id,
      objective: passport.objective,
      approved_plan_hash: passport.approved_plan_hash,
      acceptance_criteria: passport.acceptance_criteria,
      mandatory_amendments: passport.mandatory_amendments,
      allowed_file_scope: passport.allowed_file_scope,
      required_checks: passport.required_checks,
    });
    const recovery = mode === 'passport_handoff' ? `This is a new process using a compact passport handoff, not a resumed native session.\n${JSON.stringify(project(passport))}\n\n` : '';
    const instruction = `Task passport projection:\n${taskContext}\n\nDo not modify files outside allowed_file_scope when it is non-empty.\n\n${recovery}${prompt}\n\nImplement, test, and commit on the current worktree branch. End with strict JSON: job_id, status completed|partial|failed, files_changed, commands_run, tests_reported, deviations, unresolved, summary.`;
    const profile = passport.config.profiles.opus; const result = await claudeCall(this.pm, bounded(instruction, passport.config.max_input_bytes), workspace, profile.model, profile.max_turns, profile.effort, profile.timeout_ms, passport.config.max_output_bytes);
    return { value: parseJson<OpusResult>(result.text), session_id: result.sessionId ?? sessionId ?? undefined, session_mode: mode === 'passport_handoff' ? 'passport_handoff' as const : 'new' as const, resumed: false, resume_failed: mode === 'passport_handoff', usage: result.usage };
  }
  async available() { return availability('claude'); }
}

export class NativeWorkflowGitGateway implements WorkflowGitPort {
  constructor(private readonly projectRoot: string) {}
  async prepare(jobId: string) { const branch = `orchestry/workflow/${jobId}`; const worktree = path.join(this.projectRoot, '.orchestry', 'workspaces', jobId); await fs.mkdir(path.dirname(worktree), { recursive: true, mode: 0o700 }); try { await git(this.projectRoot, ['worktree', 'add', worktree, '-b', branch]); } catch { await git(this.projectRoot, ['worktree', 'prune']); await git(this.projectRoot, ['worktree', 'add', worktree, branch]); } await fs.rm(path.join(worktree, '.orchestry'), { recursive: true, force: true }); return { branch, worktree }; }
  async inspect(branch: string, worktree: string): Promise<GitEvidence> { const status = (await git(worktree, ['status', '--porcelain'])).trim(); if (status) throw new Error('Opus worktree contains uncommitted changes; review requires a committed snapshot'); const commit = (await git(worktree, ['rev-parse', 'HEAD'])).trim(); const base = (await git(this.projectRoot, ['merge-base', 'HEAD', branch])).trim(); const diff = await git(this.projectRoot, ['diff', '--binary', `${base}...${commit}`], 16 * 1024 * 1024); const files = (await git(this.projectRoot, ['diff', '--name-only', `${base}...${commit}`])).trim().split('\n').filter(Boolean); const stat = await git(this.projectRoot, ['diff', '--numstat', `${base}...${commit}`]); let insertions = 0; let deletions = 0; for (const line of stat.split('\n')) { const [a, d] = line.split('\t'); insertions += Number(a) || 0; deletions += Number(d) || 0; } const risk_signals = files.filter((file) => /auth|security|secret|migration|deploy|infra|billing/i.test(file)); return { branch, worktree, commit, diff, diff_hash: hashCanonical(diff), files_changed: files, insertions, deletions, risk_signals }; }
  async runChecks(worktree: string, commit: string, commands: string[]): Promise<CheckResults> { const checks: CheckResults['checks'] = []; for (const command of commands) { try { const { stdout, stderr } = await execFileAsync('/bin/sh', ['-lc', command], { cwd: worktree, env: buildChildEnv(), maxBuffer: 4 * 1024 * 1024 }); checks.push({ command, passed: true, output: `${stdout}${stderr}` }); } catch (error) { const e = error as Error & { stdout?: string; stderr?: string }; checks.push({ command, passed: false, output: `${e.stdout ?? ''}${e.stderr ?? e.message}` }); } } return { job_id: path.basename(worktree), commit, passed: checks.every((check) => check.passed), checks }; }
  async currentCommit(branch: string) { return (await git(this.projectRoot, ['rev-parse', branch])).trim(); }
  async isMerged(_branch: string, commit: string) { try { await git(this.projectRoot, ['merge-base', '--is-ancestor', commit, 'HEAD']); return true; } catch { return false; } }
  async merge(branch: string) { try { if (!branch.startsWith('orchestry/workflow/')) return { success: false, detail: 'Refusing to merge a non-workflow branch' }; const status = (await git(this.projectRoot, ['status', '--porcelain'])).trim(); if (status) return { success: false, detail: 'Controller worktree is dirty' }; await git(this.projectRoot, ['merge', '--no-ff', branch, '-m', `Merge ${branch}`]); return { success: true, detail: 'merged' }; } catch (error) { await git(this.projectRoot, ['merge', '--abort']).catch(() => ''); return { success: false, detail: error instanceof Error ? error.message : String(error) }; } }
}

async function claudeCall(pm: IProcessManager, prompt: string, cwd: string, model: string, maxTurns: number, effort: 'low' | 'medium' | 'high', timeout: number, maxOutput: number, toolFree = false) { const args = ['--print', '--output-format', 'stream-json', '--max-turns', String(maxTurns), '--verbose', '--model', model, '--effort', effort]; if (toolFree) args.push('--bare', '--tools', '', '--disable-slash-commands', '--strict-mcp-config', '--mcp-config', '{"mcpServers":{}}', '--no-session-persistence'); const output = await spawnCapture(pm, 'claude', args, cwd, prompt, maxOutput, timeout); let text = ''; let sessionId: string | undefined; let usage: Record<string, number> = {}; for (const line of output.split('\n').filter(Boolean).map(parseObject)) { if (line.type === 'result') { if (typeof line.result === 'string') text = line.result; if (typeof line.session_id === 'string') sessionId = line.session_id; usage = usageObject(line.usage); } } if (!text) throw new Error('Claude returned no result'); return { text, sessionId, usage: { input_chars: prompt.length, output_chars: text.length, input_tokens: usage.input_tokens, output_tokens: usage.output_tokens, cache_read: usage.cache_read_input_tokens, cache_write: usage.cache_creation_input_tokens } }; }
async function spawnCapture(pm: IProcessManager, command: string, args: string[], cwd: string, input: string, maxBytes: number, timeoutMs: number): Promise<string> { const { process: child } = pm.spawn(command, args, { cwd, env: buildChildEnv(), stdio: ['pipe', 'pipe', 'pipe'] }); let stdout = ''; let stderr = ''; let exceeded = false; let timedOut = false; const timer = setTimeout(() => { timedOut = true; child.kill('SIGTERM'); }, timeoutMs); child.stdout?.on('data', (chunk: Buffer) => { stdout += chunk.toString(); if (Buffer.byteLength(stdout) > maxBytes) { exceeded = true; child.kill(); } }); child.stderr?.on('data', (chunk: Buffer) => { if (stderr.length < 64_000) stderr += chunk.toString(); }); child.stdin?.end(input); const code = await new Promise<number>((resolve, reject) => { child.on('close', (value) => resolve(value ?? 1)); child.on('error', reject); }).finally(() => clearTimeout(timer)); if (timedOut) throw new Error(`${command} timed out after ${timeoutMs}ms`); if (exceeded) throw new Error(`${command} output exceeded configured maximum`); if (code !== 0) throw new Error(`${command} exited ${code}: ${stderr}`); return stdout; }
async function availability(command: string) { try { const { stdout } = await execFileAsync(command, ['--version'], { env: buildChildEnv() }); return { available: true, detail: stdout.trim() }; } catch { return { available: false, detail: `${command} CLI unavailable` }; } }
export async function detectWorkflowCapabilities() { return { codex: await capability('codex'), claude: await capability('claude') }; }
async function capability(command: 'codex' | 'claude') { try { const [{ stdout: version }, { stdout: help }] = await Promise.all([execFileAsync(command, ['--version'], { env: buildChildEnv(), timeout: 5_000 }), execFileAsync(command, ['--help'], { env: buildChildEnv(), timeout: 5_000, maxBuffer: 1024 * 1024 })]); const required = command === 'claude' ? ['--print', '--output-format', '--max-turns', '--model', '--effort'] : ['exec', '--json', '--sandbox']; const unsupported = required.filter((flag) => !help.includes(flag)); return { available: true, version: version.trim(), native_resume: false, supported_options: required.filter((flag) => help.includes(flag)), unsupported_options: unsupported, detail: unsupported.length ? `Unsupported required options: ${unsupported.join(', ')}` : 'Required workflow options detected; native resume remains disabled until an end-to-end probe is verified.' }; } catch { return { available: false, version: null, native_resume: false, supported_options: [], unsupported_options: [], detail: `${command} CLI unavailable` }; } }
async function git(cwd: string, args: string[], maxBuffer = 4 * 1024 * 1024) { const { stdout } = await execFileAsync('git', args, { cwd, env: buildChildEnv(), maxBuffer }); return stdout; }
function parseObject(line: string): Record<string, unknown> { try { return JSON.parse(line) as Record<string, unknown>; } catch { return {}; } }
function object(value: unknown): Record<string, unknown> { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function usageObject(value: unknown): Record<string, number> { const result: Record<string, number> = {}; for (const [key, nested] of Object.entries(object(value))) if (typeof nested === 'number') result[key] = nested; return result; }
function parseJson<T>(text: string): T { const trimmed = text.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, ''); try { return JSON.parse(trimmed) as T; } catch { throw new Error('Role returned malformed JSON'); } }
function bounded(value: string, max: number): string { if (Buffer.byteLength(value) > max) throw new Error('Role input exceeded configured maximum'); return value; }
function project(passport: WorkflowPassportV1) { return { schema_version: passport.schema_version, job_id: passport.job_id, objective: passport.objective, acceptance_criteria: passport.acceptance_criteria, mandatory_amendments: passport.mandatory_amendments, current_phase: passport.current_phase, current_revision: passport.current_revision, approved_plan_hash: passport.approved_plan_hash, allowed_file_scope: passport.allowed_file_scope, required_checks: passport.required_checks, current_blockers: passport.current_blockers, next_action: passport.next_action, current_commit: passport.current_commit }; }
