export const GOVERNANCE_SCHEMA_VERSION = 3 as const;
export const GOVERNANCE_KINDS = ['binding_snapshot', 'decomposition_plan', 'check_binding', 'candidate_evidence', 'review_vote', 'quorum_policy', 'quorum_result', 'integration_receipt', 'human_approval'] as const;
export type GovernanceRecordKindV3 = typeof GOVERNANCE_KINDS[number];
export type GovernanceActorRoleV3 = 'planner' | 'candidate' | 'reviewer' | 'checker' | 'integrator';

interface Base { schema_version: 3; kind: GovernanceRecordKindV3; governance_id: string; record_id: string; }
export interface GovernanceRefV3<K extends GovernanceRecordKindV3 = GovernanceRecordKindV3> { kind: K; record_id: string; record_hash: string; }
export interface GovernanceActorBindingV3 { binding_id: string; role: GovernanceActorRoleV3; principal_id: string; adapter: string; model: string; }
export interface GovernanceCheckProvenanceV3 { command_source: 'trusted'; execution_environment: 'sandboxed'; }
export interface BindingSnapshotV3 extends Base { kind: 'binding_snapshot'; bindings: GovernanceActorBindingV3[]; created_at: string; }
export interface DecompositionUnitV3 { unit_id: string; objective: string; depends_on: string[]; owned_path_prefixes: string[]; acceptance_criteria: string[]; required_check_ids: string[]; }
export interface DecompositionPlanV3 extends Base { kind: 'decomposition_plan'; binding_snapshot: GovernanceRefV3<'binding_snapshot'>; objective: string; base_commit: string; target_branch: string; units: DecompositionUnitV3[]; integration_check_ids: string[]; created_by_binding_id: string; created_at: string; }
export interface CheckBindingV3 extends Base { kind: 'check_binding'; binding_snapshot: GovernanceRefV3<'binding_snapshot'>; subject: { kind: 'candidate' | 'integration'; id: string; commit: string }; check_id: string; command: string; status: 'passed' | 'failed'; output_hash: string; executed_by_binding_id: string; provenance: GovernanceCheckProvenanceV3; started_at: string; completed_at: string; }
export interface CandidateEvidenceV3 extends Base { kind: 'candidate_evidence'; plan: GovernanceRefV3<'decomposition_plan'>; binding_snapshot: GovernanceRefV3<'binding_snapshot'>; unit_id: string; candidate_id: string; produced_by_binding_id: string; base_commit: string; commit: string; diff_hash: string; changed_paths: string[]; check_bindings: GovernanceRefV3<'check_binding'>[]; summary: string; created_at: string; }
export type ReviewSubjectRefV3 = GovernanceRefV3<'candidate_evidence'> | GovernanceRefV3<'integration_receipt'>;
export interface ReviewVoteV3 extends Base { kind: 'review_vote'; binding_snapshot: GovernanceRefV3<'binding_snapshot'>; subject: ReviewSubjectRefV3; reviewer_binding_id: string; decision: 'approve' | 'reject'; reason: string; cast_at: string; }
export interface QuorumPolicyV3 extends Base { kind: 'quorum_policy'; binding_snapshot: GovernanceRefV3<'binding_snapshot'>; applies_to: 'candidate_evidence' | 'integration_receipt'; eligible_reviewer_binding_ids: string[]; minimum_approvals: number; maximum_rejections: number; require_distinct_principals: boolean; human_approval_required: boolean; created_by_binding_id: string; created_at: string; }
export interface HumanApprovalV3 extends Base { kind: 'human_approval'; subject: ReviewSubjectRefV3; approved_by: string; reason: string; approved_at: string; }
export interface QuorumResultV3 extends Base { kind: 'quorum_result'; policy: GovernanceRefV3<'quorum_policy'>; subject: ReviewSubjectRefV3; votes: GovernanceRefV3<'review_vote'>[]; human_approval: GovernanceRefV3<'human_approval'> | null; approvals: number; rejections: number; satisfied: boolean; evaluated_at: string; }
export interface IntegrationReceiptV3 extends Base { kind: 'integration_receipt'; plan: GovernanceRefV3<'decomposition_plan'>; binding_snapshot: GovernanceRefV3<'binding_snapshot'>; integrated_by_binding_id: string; target_branch: string; base_commit: string; candidates: Array<{ evidence: GovernanceRefV3<'candidate_evidence'>; quorum_result: GovernanceRefV3<'quorum_result'> }>; integrated_commit: string; diff_hash: string; check_bindings: GovernanceRefV3<'check_binding'>[]; integrated_at: string; }
export type GovernanceRecordV3 = BindingSnapshotV3 | DecompositionPlanV3 | CheckBindingV3 | CandidateEvidenceV3 | ReviewVoteV3 | QuorumPolicyV3 | QuorumResultV3 | IntegrationReceiptV3 | HumanApprovalV3;
export interface StoredGovernanceRecordV3<T extends GovernanceRecordV3 = GovernanceRecordV3> { storage_version: 1; record_hash: string; record_hmac: string; record: T; }

const ID = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
const HASH = /^[a-f0-9]{64}$/;
const COMMIT = /^[a-f0-9]{40,64}$/;
const MAX_ITEMS = 256;
const MAX_TEXT = 128_000;

export function validateGovernanceRecordV3(value: unknown): GovernanceRecordV3 {
  const o = record(value, 'governance record');
  const kind = one(o.kind, GOVERNANCE_KINDS, 'kind');
  if (kind === 'binding_snapshot') return validateBindingSnapshotV3(o);
  if (kind === 'decomposition_plan') return validateDecompositionPlanV3(o);
  if (kind === 'check_binding') return validateCheckBindingV3(o);
  if (kind === 'candidate_evidence') return validateCandidateEvidenceV3(o);
  if (kind === 'review_vote') return validateReviewVoteV3(o);
  if (kind === 'quorum_policy') return validateQuorumPolicyV3(o);
  if (kind === 'quorum_result') return validateQuorumResultV3(o);
  if (kind === 'integration_receipt') return validateIntegrationReceiptV3(o);
  return validateHumanApprovalV3(o);
}

export function validateBindingSnapshotV3(value: unknown): BindingSnapshotV3 {
  const o = exact(value, ['schema_version', 'kind', 'governance_id', 'record_id', 'bindings', 'created_at'], 'binding snapshot'); base(o, 'binding_snapshot');
  const bindings = unique(items(o.bindings, 'bindings').map((v, i) => { const b = exact(v, ['binding_id', 'role', 'principal_id', 'adapter', 'model'], `bindings[${i}]`); return { binding_id: id(b.binding_id), role: one(b.role, ['planner', 'candidate', 'reviewer', 'checker', 'integrator'] as const, 'role'), principal_id: id(b.principal_id), adapter: id(b.adapter), model: short(b.model, 'model', true) }; }), (b) => b.binding_id, 'binding IDs');
  if (!bindings.length) throw new Error('bindings must not be empty');
  return { ...base(o, 'binding_snapshot'), bindings, created_at: timestamp(o.created_at) };
}
export function validateDecompositionPlanV3(value: unknown): DecompositionPlanV3 {
  const o = exact(value, ['schema_version', 'kind', 'governance_id', 'record_id', 'binding_snapshot', 'objective', 'base_commit', 'target_branch', 'units', 'integration_check_ids', 'created_by_binding_id', 'created_at'], 'decomposition plan');
  const units = unique(items(o.units, 'units').map((v, i) => { const u = exact(v, ['unit_id', 'objective', 'depends_on', 'owned_path_prefixes', 'acceptance_criteria', 'required_check_ids'], `units[${i}]`); const paths = unique(strings(u.owned_path_prefixes, 'owned_path_prefixes').map(safePath), String, 'owned paths'); if (!paths.length) throw new Error('owned_path_prefixes must not be empty'); return { unit_id: id(u.unit_id), objective: short(u.objective, 'objective'), depends_on: unique(strings(u.depends_on, 'depends_on').map(id), String, 'dependencies'), owned_path_prefixes: paths, acceptance_criteria: strings(u.acceptance_criteria, 'acceptance_criteria'), required_check_ids: unique(strings(u.required_check_ids, 'required_check_ids').map(id), String, 'check IDs') }; }), (u) => u.unit_id, 'unit IDs');
  if (!units.length) throw new Error('units must not be empty'); validateDag(units);
  return { ...base(o, 'decomposition_plan'), binding_snapshot: ref(o.binding_snapshot, 'binding_snapshot'), objective: short(o.objective, 'objective'), base_commit: commit(o.base_commit), target_branch: branch(o.target_branch), units, integration_check_ids: unique(strings(o.integration_check_ids, 'integration_check_ids').map(id), String, 'integration check IDs'), created_by_binding_id: id(o.created_by_binding_id), created_at: timestamp(o.created_at) };
}
export function validateCheckBindingV3(value: unknown): CheckBindingV3 { const o = exact(value, ['schema_version','kind','governance_id','record_id','binding_snapshot','subject','check_id','command','status','output_hash','executed_by_binding_id','provenance','started_at','completed_at'], 'check binding'); const s = exact(o.subject, ['kind','id','commit'], 'check subject'); const p = exact(o.provenance, ['command_source','execution_environment'], 'check provenance'); const started = timestamp(o.started_at); const completed = timestamp(o.completed_at); if (completed < started) throw new Error('completed_at precedes started_at'); return { ...base(o,'check_binding'), binding_snapshot: ref(o.binding_snapshot,'binding_snapshot'), subject: { kind: one(s.kind,['candidate','integration'] as const,'subject kind'), id: id(s.id), commit: commit(s.commit) }, check_id: id(o.check_id), command: short(o.command,'command'), status: one(o.status,['passed','failed'] as const,'status'), output_hash: hash(o.output_hash), executed_by_binding_id: id(o.executed_by_binding_id), provenance: { command_source: one(p.command_source,['trusted'] as const,'command source'), execution_environment: one(p.execution_environment,['sandboxed'] as const,'execution environment') }, started_at: started, completed_at: completed }; }
export function validateCandidateEvidenceV3(value: unknown): CandidateEvidenceV3 { const o = exact(value, ['schema_version','kind','governance_id','record_id','plan','binding_snapshot','unit_id','candidate_id','produced_by_binding_id','base_commit','commit','diff_hash','changed_paths','check_bindings','summary','created_at'], 'candidate evidence'); const baseCommit=commit(o.base_commit), candidateCommit=commit(o.commit); if(baseCommit===candidateCommit) throw new Error('candidate commit must differ from base'); return { ...base(o,'candidate_evidence'), plan: ref(o.plan,'decomposition_plan'), binding_snapshot: ref(o.binding_snapshot,'binding_snapshot'), unit_id:id(o.unit_id), candidate_id:id(o.candidate_id), produced_by_binding_id:id(o.produced_by_binding_id), base_commit:baseCommit, commit:candidateCommit, diff_hash:hash(o.diff_hash), changed_paths:unique(strings(o.changed_paths,'changed_paths').map(safePath),String,'changed paths'), check_bindings:refs(o.check_bindings,'check_binding'), summary:short(o.summary,'summary'), created_at:timestamp(o.created_at) }; }
export function validateReviewVoteV3(value: unknown): ReviewVoteV3 { const o=exact(value,['schema_version','kind','governance_id','record_id','binding_snapshot','subject','reviewer_binding_id','decision','reason','cast_at'],'review vote'); return {...base(o,'review_vote'),binding_snapshot:ref(o.binding_snapshot,'binding_snapshot'),subject:subjectRef(o.subject),reviewer_binding_id:id(o.reviewer_binding_id),decision:one(o.decision,['approve','reject'] as const,'decision'),reason:short(o.reason,'reason'),cast_at:timestamp(o.cast_at)}; }
export function validateQuorumPolicyV3(value: unknown): QuorumPolicyV3 { const o=exact(value,['schema_version','kind','governance_id','record_id','binding_snapshot','applies_to','eligible_reviewer_binding_ids','minimum_approvals','maximum_rejections','require_distinct_principals','human_approval_required','created_by_binding_id','created_at'],'quorum policy'); const eligible=unique(strings(o.eligible_reviewer_binding_ids,'eligible reviewers').map(id),String,'eligible reviewers'); const minimum=integer(o.minimum_approvals,'minimum_approvals'); if(!eligible.length||minimum<1||minimum>eligible.length) throw new Error('invalid quorum minimum'); return {...base(o,'quorum_policy'),binding_snapshot:ref(o.binding_snapshot,'binding_snapshot'),applies_to:one(o.applies_to,['candidate_evidence','integration_receipt'] as const,'applies_to'),eligible_reviewer_binding_ids:eligible,minimum_approvals:minimum,maximum_rejections:integer(o.maximum_rejections,'maximum_rejections'),require_distinct_principals:bool(o.require_distinct_principals),human_approval_required:bool(o.human_approval_required),created_by_binding_id:id(o.created_by_binding_id),created_at:timestamp(o.created_at)}; }
export function validateHumanApprovalV3(value: unknown): HumanApprovalV3 { const o=exact(value,['schema_version','kind','governance_id','record_id','subject','approved_by','reason','approved_at'],'human approval'); return {...base(o,'human_approval'),subject:subjectRef(o.subject),approved_by:short(o.approved_by,'approved_by'),reason:short(o.reason,'reason'),approved_at:timestamp(o.approved_at)}; }
export function validateQuorumResultV3(value: unknown): QuorumResultV3 { const o=exact(value,['schema_version','kind','governance_id','record_id','policy','subject','votes','human_approval','approvals','rejections','satisfied','evaluated_at'],'quorum result'); const votes=refs(o.votes,'review_vote'), approvals=integer(o.approvals,'approvals'), rejections=integer(o.rejections,'rejections'); if(approvals+rejections!==votes.length) throw new Error('quorum counts do not match votes'); return {...base(o,'quorum_result'),policy:ref(o.policy,'quorum_policy'),subject:subjectRef(o.subject),votes,human_approval:o.human_approval===null?null:ref(o.human_approval,'human_approval'),approvals,rejections,satisfied:bool(o.satisfied),evaluated_at:timestamp(o.evaluated_at)}; }
export function validateIntegrationReceiptV3(value: unknown): IntegrationReceiptV3 { const o=exact(value,['schema_version','kind','governance_id','record_id','plan','binding_snapshot','integrated_by_binding_id','target_branch','base_commit','candidates','integrated_commit','diff_hash','check_bindings','integrated_at'],'integration receipt'); const candidates=items(o.candidates,'candidates').map((v,i)=>{const c=exact(v,['evidence','quorum_result'],`candidates[${i}]`);return{evidence:ref(c.evidence,'candidate_evidence'),quorum_result:ref(c.quorum_result,'quorum_result')}}); unique(candidates,(c)=>c.evidence.record_id,'integration candidates'); if(!candidates.length) throw new Error('integration candidates must not be empty'); return {...base(o,'integration_receipt'),plan:ref(o.plan,'decomposition_plan'),binding_snapshot:ref(o.binding_snapshot,'binding_snapshot'),integrated_by_binding_id:id(o.integrated_by_binding_id),target_branch:branch(o.target_branch),base_commit:commit(o.base_commit),candidates,integrated_commit:commit(o.integrated_commit),diff_hash:hash(o.diff_hash),check_bindings:refs(o.check_bindings,'check_binding'),integrated_at:timestamp(o.integrated_at)}; }

function base<K extends GovernanceRecordKindV3>(o: Record<string,unknown>, kind: K): Base & {kind:K} { if(o.schema_version!==3||o.kind!==kind) throw new Error(`Expected governance ${kind} schema v3`); return {schema_version:3,kind,governance_id:id(o.governance_id),record_id:id(o.record_id)}; }
function ref<K extends GovernanceRecordKindV3>(v:unknown,kind:K):GovernanceRefV3<K>{const o=exact(v,['kind','record_id','record_hash'],'reference');if(o.kind!==kind)throw new Error(`Expected ${kind} reference`);return{kind,record_id:id(o.record_id),record_hash:hash(o.record_hash)}}
function refs<K extends GovernanceRecordKindV3>(v:unknown,k:K){return unique(items(v,'references').map((x)=>ref(x,k)),(x)=>x.record_id,'references')}
function subjectRef(v:unknown):ReviewSubjectRefV3{const o=record(v,'subject');return o.kind==='candidate_evidence'?ref(o,'candidate_evidence'):ref(o,'integration_receipt')}
function validateDag(units:DecompositionUnitV3[]){const ids=new Set(units.map(u=>u.unit_id));for(const u of units)for(const d of u.depends_on)if(!ids.has(d)||d===u.unit_id)throw new Error('Invalid unit dependency');const visiting=new Set<string>(),done=new Set<string>();const visit=(id:string)=>{if(visiting.has(id))throw new Error('Decomposition cycle');if(done.has(id))return;visiting.add(id);for(const d of units.find(u=>u.unit_id===id)!.depends_on)visit(d);visiting.delete(id);done.add(id)};for(const u of units)visit(u.unit_id)}
function exact(v:unknown,keys:string[],label:string){const o=record(v,label),set=new Set(keys);for(const k of keys)if(!(k in o))throw new Error(`${label} missing ${k}`);for(const k of Object.keys(o))if(!set.has(k))throw new Error(`${label} unknown field ${k}`);return o}
function record(v:unknown,label:string):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error(`${label} must be an object`);return v as Record<string,unknown>}
function items(v:unknown,label:string){if(!Array.isArray(v)||v.length>MAX_ITEMS)throw new Error(`${label} must be a bounded array`);return v}
function strings(v:unknown,label:string){return items(v,label).map((x)=>short(x,label,true))}
function short(v:unknown,label:string,empty=false){if(typeof v!=='string'||v.length>MAX_TEXT||(!empty&&!v.trim()))throw new Error(`${label} is invalid`);return v}
function id(v:unknown){const s=short(v,'id');if(!ID.test(s))throw new Error('Invalid id');return s}
function hash(v:unknown){const s=short(v,'hash');if(!HASH.test(s))throw new Error('Invalid SHA-256 hash');return s}
function commit(v:unknown){const s=short(v,'commit');if(!COMMIT.test(s))throw new Error('Invalid commit');return s}
export function validateGovernanceBranchV3(v:unknown):string{const s=short(v,'branch');if(s.length>255||s==='@'||s.startsWith('-')||s.startsWith('/')||s.startsWith('refs/')||s.endsWith('/')||s.endsWith('.')||s.includes('..')||s.includes('//')||s.includes('@{')||/[\\\x00-\x20~^:?*[\]]/.test(s)||s.split('/').some((part)=>!part||part.startsWith('.')||part.endsWith('.lock')))throw new Error('Invalid Git branch name');return s}
function branch(v:unknown){return validateGovernanceBranchV3(v)}
function timestamp(v:unknown){const s=short(v,'timestamp');if(!Number.isFinite(Date.parse(s))||new Date(s).toISOString()!==s)throw new Error('Invalid canonical timestamp');return s}
function integer(v:unknown,label:string){if(!Number.isSafeInteger(v)||(v as number)<0)throw new Error(`${label} must be a nonnegative integer`);return v as number}
function bool(v:unknown){if(typeof v!=='boolean')throw new Error('Expected boolean');return v}
function one<const T extends readonly string[]>(v:unknown,allowed:T,label:string):T[number]{if(typeof v!=='string'||!allowed.includes(v))throw new Error(`Invalid ${label}`);return v as T[number]}
function safePath(v:string){if(v.startsWith('/')||v.includes('\\')||v.split('/').some(p=>!p||p==='.'||p==='..'))throw new Error('Unsafe governance path');return v}
function unique<T>(values:T[],key:(v:T)=>string,label:string){const seen=new Set<string>();for(const v of values){const k=key(v);if(seen.has(k))throw new Error(`Duplicate ${label}`);seen.add(k)}return values}
