import { describe, expect, it } from 'vitest';
import { validateCodexDecision, validateFableAdvice, validateOpusResult } from '../../../src/domain/workflow/contracts.js';

const base = { schema_version: 2, job_id: 'wf_1', summary: 'ok', implementation_brief: null, required_changes: [], risk_level: 'low', fable_query: null, reviewed_commit: null, fable_advice_disposition: null, fable_error: null, fable_iteration_effect: null } as const;
describe('workflow contracts v2', () => {
  it('validates direct phase actions and rejects premature ACCEPT', () => { expect(validateCodexDecision({ ...base, action: 'DISPATCH_OPUS', implementation_brief: 'implement' }, 'pre_opus').action).toBe('DISPATCH_OPUS'); expect(() => validateCodexDecision({ ...base, action: 'ACCEPT' }, 'pre_opus')).toThrow('invalid during pre_opus'); });
  it('requires exact bounded Fable query fields and lets the engine deny high risk', () => { const fable_query = { purpose: 'COMPARE_BOUNDED_OPTIONS', question: 'A or B?', verification_method: 'compare tests', fallback_if_skipped: { action: 'DISPATCH_OPUS', instructions: 'use A' } }; expect(validateCodexDecision({ ...base, action: 'CONSULT_FABLE', fable_query }, 'pre_opus').fable_query).toEqual(fable_query); expect(validateCodexDecision({ ...base, action: 'CONSULT_FABLE', risk_level: 'high', fable_query }, 'pre_opus').risk_level).toBe('high'); });
  it('requires explicit Fable outcome accounting after consultation', () => { expect(() => validateCodexDecision({ ...base, action: 'DISPATCH_OPUS', implementation_brief: 'x' }, 'after_fable_pre')).toThrow('must record'); expect(validateCodexDecision({ ...base, action: 'DISPATCH_OPUS', implementation_brief: 'x', fable_advice_disposition: 'rejected', fable_error: 'unsupported claim', fable_iteration_effect: 'unchanged' }, 'after_fable_pre')).toMatchObject({ fable_advice_disposition: 'rejected', fable_iteration_effect: 'unchanged' }); });
  it('rejects phase-invalid consultation fallback actions', () => { const query = { purpose: 'COMPARE_BOUNDED_OPTIONS', question: 'A or B?', verification_method: 'tests', fallback_if_skipped: { action: 'CORRECT_OPUS', instructions: 'fix' } }; expect(() => validateCodexDecision({ ...base, action: 'CONSULT_FABLE', fable_query: query }, 'pre_opus')).toThrow('cannot use CORRECT_OPUS'); });
  it('keeps Fable advice advisory-only and exact', () => { expect(validateFableAdvice({ schema_version: 1, consultation_id: 'consult_1', answer: 'A', alternatives: ['B'], uncertainties: [] }).answer).toBe('A'); expect(() => validateFableAdvice({ schema_version: 1, consultation_id: 'consult_1', answer: 'A', alternatives: [], uncertainties: [], action: 'ACCEPT' })).toThrow('unknown field action'); });
  it('retains strict Opus statuses', () => { expect(validateOpusResult({ job_id: 'wf_1', status: 'completed', files_changed: [], commands_run: [], tests_reported: [], deviations: [], unresolved: [], summary: 'done' }).status).toBe('completed'); expect(() => validateOpusResult({ job_id: 'wf_1', status: 'done' })).toThrow(); });
});
