import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { Command } from 'commander';
import type { Container } from '../../container.js';

export function registerWorkflowCommand(program: Command, container: Container): void {
  const workflow = program.command('workflow').description('Recoverable Codex-Fable-Opus workflow');
  workflow.command('start <objective>').description('Start and run the workflow in the foreground').option('--pipeline <name>', 'Pipeline name', 'codex-fable-opus').option('--check <command...>', 'Mandatory deterministic checks').option('--allow <path...>', 'Allowed file scope').option('--post-review <mode>', 'risk_based|always|never', 'risk_based').action(async (objective: string, options: { pipeline: string; check?: string[]; allow?: string[]; postReview: string }) => {
    if (options.pipeline !== 'codex-fable-opus') throw new Error(`Unsupported pipeline: ${options.pipeline}`);
    if (!['risk_based', 'always', 'never'].includes(options.postReview)) throw new Error('Invalid --post-review mode');
    const id = await container.workflowEngine.start({ objective, allowed_file_scope: options.allow, required_checks: options.check, config: { post_review: options.postReview as 'risk_based' | 'always' | 'never' } });
    console.log(id); // Printed before foreground execution so the job remains discoverable after interruption.
    const result = await container.workflowEngine.run(id); if (result.phase === 'failed') process.exitCode = 1;
  });
  workflow.command('status [job-id]').description('Show workflow status (latest when omitted)').action(async (requested: string | undefined) => { const id = requested ?? (await container.workflowStore.listJobs())[0]?.job_id; if (!id) throw new Error('No workflows found'); const [job, sessions, passport] = await Promise.all([container.workflowStore.readJob(id), container.workflowStore.readSessions(id), container.workflowStore.readPassport(id)]); if (!job || !sessions || !passport) throw new Error(`Workflow job not found: ${id}`); print(container, { job_id: id, phase: job.phase, current_agent: agentFor(job.phase), revision: job.revision, opus_iteration: job.opus_iteration, fable_calls: { pre_opus: `${job.fable_pre_opus_calls}/${passport.config.fable_pre_opus_cap}`, post_opus: job.fable_post_opus_calls, total: `${job.fable_total_calls}/${passport.config.fable_total_cap}` }, branch: job.branch, commit: job.current_commit, last_verdict: job.last_verdict, blocker: job.blocker, next_action: job.next_action, session_modes: sessions.modes, rotation_history: sessions.rotation_history, usage: sessions.usage }); });
  workflow.command('pause <job-id>').description('Pause a workflow').action(async (id: string) => { print(container, await container.workflowEngine.pause(id)); });
  workflow.command('resume <job-id>').description('Resume and run a workflow in the foreground').option('--approve-stop', 'Explicitly approve continuing after STOP').action(async (id: string, options: { approveStop?: boolean }) => { const result = await container.workflowEngine.resume(id, options.approveStop); print(container, result); if (result.phase === 'failed') process.exitCode = 1; });
  workflow.command('session-rotate <job-id> <role>').description('Rotate a codex, fable, or opus session').option('--reason <reason>', 'Audit reason', 'manual rotation').action(async (id: string, role: string, options: { reason: string }) => { if (!['codex', 'fable', 'opus'].includes(role)) throw new Error('Role must be codex, fable, or opus'); await container.workflowEngine.rotateSession(id, role as 'codex' | 'fable' | 'opus', options.reason); print(container, { job_id: id, role, rotated: true }); });
  workflow.command('cancel <job-id>').description('Cancel a workflow').action(async (id: string) => { print(container, await container.workflowEngine.cancel(id)); });
  workflow.command('logs <job-id>').description('Show durable workflow events').action(async (id: string) => { const events = await container.workflowStore.readEvents(id); if (container.context.json) console.log(JSON.stringify(events, null, 2)); else for (const event of events) console.log(`${event.timestamp} ${event.type} ${JSON.stringify(event.data)}`); });
  workflow.command('artifacts <job-id>').description('List canonical workflow artifacts').action(async (id: string) => { const passport = await container.workflowStore.readPassport(id); if (!passport) throw new Error(`Workflow job not found: ${id}`); const root = path.join(container.context.projectRoot, '.orchestry', 'workflows', id, 'artifacts'); print(container, passport.artifacts.map((item) => ({ ...item, path: path.join(root, item.filename) }))); });
  workflow.command('doctor').description('Check native workflow CLIs and readiness').action(async () => { const { detectWorkflowCapabilities } = await import('../../infrastructure/workflow/native-adapters.js'); const capabilities = await detectWorkflowCapabilities(); const latest = (await container.workflowStore.listJobs())[0]; const passport = latest ? await container.workflowStore.readPassport(latest.job_id) : null; const meaningfulChecks = (passport?.required_checks.length ?? 0) > 0; const blocked = !capabilities.codex.available || !capabilities.claude.available; print(container, { node: process.version, git: await gitVersion(), codex: capabilities.codex, claude: capabilities.claude, session_resume: { codex: capabilities.codex.native_resume ? 'native_resume' : 'passport_handoff', opus: capabilities.claude.native_resume ? 'native_resume' : 'passport_handoff' }, configuration: path.join(container.context.projectRoot, '.orchestry', 'config.yml'), dangerous_execution: process.env.ORCHESTRY_ALLOW_DANGEROUS_EXECUTION === '1' ? 'environment opt-in present; project config still required' : 'disabled', meaningful_verification: meaningfulChecks, readiness: blocked ? 'blocked' : meaningfulChecks ? 'ready' : 'degraded' }); });
}

function print(container: Container, value: unknown): void { console.log(JSON.stringify(value, null, container.context.json ? 2 : 2)); }
function agentFor(phase: string): string | null { if (phase.startsWith('codex')) return 'codex'; if (phase.startsWith('fable')) return 'fable'; if (phase === 'opus_execution') return 'opus'; return null; }
async function gitVersion(): Promise<string> { try { return (await promisify(execFile)('git', ['--version'])).stdout.trim(); } catch { return 'unavailable'; } }
