import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { Command } from 'commander';
import type { Container } from '../../container.js';
import type { WorkflowMode } from '../../domain/workflow/state.js';

export function registerWorkflowCommand(program: Command, container: Container): void {
  const workflow = program.command('workflow').description('Recoverable direct Codex-Opus workflow');
  workflow.command('start <objective>').description('Start and run the workflow in the foreground').option('--mode <mode>', 'Workflow mode: adaptive or direct', 'adaptive').option('--check <command...>', 'Mandatory deterministic checks').option('--allow <path...>', 'Allowed file scope').action(async (objective: string, options: { mode: string; check?: string[]; allow?: string[] }) => {
    if (options.mode !== 'adaptive' && options.mode !== 'direct') throw new Error('Mode must be adaptive or direct');
    const id = await container.workflowEngine.start({ objective, mode: options.mode as WorkflowMode, allowed_file_scope: options.allow, required_checks: options.check, config: container.config.workflow });
    console.log(id); const result = await container.workflowEngine.run(id); if (result.phase === 'failed') process.exitCode = 1;
  });
  workflow.command('status [job-id]').description('Show workflow status (latest when omitted)').action(async (requested: string | undefined) => { const id = requested ?? (await container.workflowStore.listJobs())[0]?.job_id; if (!id) throw new Error('No workflows found'); const [job, sessions, passport] = await Promise.all([container.workflowStore.readJob(id), container.workflowStore.readSessions(id), container.workflowStore.readPassport(id)]); if (!job || !sessions || !passport) throw new Error(`Workflow job not found: ${id}`); const value = { job_id: id, mode: job.mode, phase: job.phase, current_agent: agentFor(job.phase), revision: job.revision, opus_iteration: job.opus_iteration, fable: { calls: job.fable_calls, cap: passport.config.fable_total_cap, consultation_status: job.consultation_status, origin: job.consultation_origin }, branch: job.branch, target_branch: job.target_branch, commit: job.current_commit, last_action: job.last_action, blocker: job.blocker, next_action: job.next_action, session_modes: sessions.modes, rotation_history: sessions.rotation_history, usage: sessions.usage }; if (container.context.json) print(container, value); else console.log([`Workflow ${id}: ${job.phase} (${job.mode})`, `Revision ${job.revision}, implementation iteration ${job.opus_iteration}`, `Optional Fable: ${job.fable_calls}/${passport.config.fable_total_cap}; ${job.consultation_status}`, `Context: Codex ${sessions.modes.codex}; Opus ${sessions.modes.opus}`, job.blocker ? `Blocked: ${job.blocker}` : `Next: ${job.next_action}`].join('\n')); });
  workflow.command('pause <job-id>').description('Pause a workflow').action(async (id: string) => { print(container, await container.workflowEngine.pause(id)); });
  workflow.command('resume <job-id>').description('Resume and run a workflow in the foreground').option('--retry-invocation', 'Explicitly retry an interrupted non-Fable call with no durable result').requiredOption('--reason <reason>', 'Audit reason for resuming').action(async (id: string, options: { retryInvocation?: boolean; reason: string }) => { const result = await container.workflowEngine.resume(id, { retry_invocation: options.retryInvocation, reason: options.reason }); print(container, result); if (result.phase === 'failed') process.exitCode = 1; });
  workflow.command('session-rotate <job-id> <role>').description('Rotate a codex or opus session').option('--reason <reason>', 'Audit reason', 'manual rotation').action(async (id: string, role: string, options: { reason: string }) => { if (role !== 'codex' && role !== 'opus') throw new Error('Role must be codex or opus; Fable is stateless'); await container.workflowEngine.rotateSession(id, role, options.reason); print(container, { job_id: id, role, rotated: true }); });
  workflow.command('cancel <job-id>').description('Cancel a workflow').action(async (id: string) => { print(container, await container.workflowEngine.cancel(id)); });
  workflow.command('logs <job-id>').description('Show durable workflow events').option('--raw', 'Show raw event data').action(async (id: string, options: { raw?: boolean }) => { const events = await container.workflowStore.readEvents(id); if (container.context.json || options.raw) console.log(JSON.stringify(events, null, 2)); else for (const event of events) console.log(`${event.timestamp} ${event.type}${event.type === 'phase_changed' ? `: ${(event.data as { from?: string }).from} -> ${(event.data as { to?: string }).to}` : ''}`); });
  workflow.command('artifacts <job-id>').description('List canonical workflow artifacts').action(async (id: string) => { const passport = await container.workflowStore.readPassport(id); if (!passport) throw new Error(`Workflow job not found: ${id}`); const root = path.join(container.context.projectRoot, '.orchestry', 'workflows', id, 'artifacts'); const artifacts = passport.artifacts.map((item) => ({ ...item, path: path.join(root, item.filename) })); if (container.context.json) print(container, artifacts); else for (const item of artifacts) console.log(`r${item.revision} i${item.iteration} ${item.phase} ${item.role}: ${item.filename}`); });
  workflow.command('doctor').description('Check direct workflow CLIs and readiness').action(async () => { const { detectWorkflowCapabilities } = await import('../../infrastructure/workflow/native-adapters.js'); const capabilities = await detectWorkflowCapabilities(); const latest = (await container.workflowStore.listJobs())[0]; const passport = latest ? await container.workflowStore.readPassport(latest.job_id) : null; const meaningfulChecks = (passport?.required_checks.length ?? 0) > 0; const nodeCompatible = Number(process.versions.node.split('.')[0]) >= 20; const git = await gitVersion(); const codexReady = capabilities.codex.available && capabilities.codex.unsupported_options.length === 0; const opusReady = capabilities.claude.available && capabilities.claude.unsupported_options.length === 0; const fableReady = capabilities.fable.available && capabilities.fable.unsupported_options.length === 0; const blocked = !nodeCompatible || git === 'unavailable' || !codexReady || !opusReady; print(container, { node: { version: process.version, compatible: nodeCompatible }, git, codex: { ...capabilities.codex, ready: codexReady }, opus: { ...capabilities.claude, ready: opusReady }, optional_fable: { ...capabilities.fable, ready: fableReady, availability_does_not_block_direct_mode: true }, configured_models: { codex: container.config.workflow?.profiles?.codex?.model ?? 'codex', fable: container.config.workflow?.profiles?.fable?.model ?? 'fable', opus: container.config.workflow?.profiles?.opus?.model ?? 'opus' }, session_resume: { codex: capabilities.codex.native_resume ? 'native_resume' : capabilities.codex.advertised_native_resume ? 'passport_handoff_unverified' : 'passport_handoff', opus: capabilities.claude.native_resume ? 'native_resume' : capabilities.claude.advertised_native_resume ? 'passport_handoff_unverified' : 'passport_handoff' }, configuration: path.join(container.context.projectRoot, '.orchestry', 'config.yml'), dangerous_execution: container.config.execution.security.allow_permission_bypass && process.env.ORCHESTRY_ALLOW_DANGEROUS_EXECUTION === '1' ? 'enabled' : 'disabled', meaningful_verification: meaningfulChecks, readiness: blocked ? 'blocked' : meaningfulChecks ? 'ready' : 'degraded' }); });
}

function print(container: Container, value: unknown): void { console.log(JSON.stringify(value, null, container.context.json ? 2 : 2)); }
function agentFor(phase: string): string | null { if (phase.startsWith('codex')) return 'codex'; if (phase === 'fable_consultation') return 'fable'; if (phase === 'opus_execution') return 'opus'; return null; }
async function gitVersion(): Promise<string> { try { return (await promisify(execFile)('git', ['--version'])).stdout.trim(); } catch { return 'unavailable'; } }
