import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { Command } from 'commander';
import type { Container } from '../../container.js';

export function registerWorkflowCommand(program: Command, container: Container): void {
  const workflow = program.command('workflow').description('Recoverable Codex-Fable-Opus workflow');
  workflow.command('start <objective>').description('Start and run the workflow in the foreground').option('--pipeline <name>', 'Pipeline name', 'codex-fable-opus').option('--check <command...>', 'Mandatory deterministic checks').option('--allow <path...>', 'Allowed file scope').option('--fable-total-cap <count>', 'Stricter whole-workflow Fable cap').action(async (objective: string, options: { pipeline: string; check?: string[]; allow?: string[]; fableTotalCap?: string }) => {
    if (options.pipeline !== 'codex-fable-opus') throw new Error(`Unsupported pipeline: ${options.pipeline}`);
    const projectConfig = container.config.workflow ?? {}; const totalCap = options.fableTotalCap === undefined ? undefined : Number(options.fableTotalCap); if (totalCap !== undefined && (!Number.isSafeInteger(totalCap) || totalCap < 1)) throw new Error('Invalid --fable-total-cap');
    const config = { ...projectConfig, post_review: 'always' as const, ...(totalCap === undefined ? {} : { fable_total_cap: Math.min(totalCap, projectConfig.fable_total_cap ?? totalCap) }) };
    const id = await container.workflowEngine.start({ objective, allowed_file_scope: options.allow, required_checks: options.check, config });
    console.log(id); // Printed before foreground execution so the job remains discoverable after interruption.
    const result = await container.workflowEngine.run(id); if (result.phase === 'failed') process.exitCode = 1;
  });
  workflow.command('status [job-id]').description('Show workflow status (latest when omitted)').action(async (requested: string | undefined) => { const id = requested ?? (await container.workflowStore.listJobs())[0]?.job_id; if (!id) throw new Error('No workflows found'); const [job, sessions, passport] = await Promise.all([container.workflowStore.readJob(id), container.workflowStore.readSessions(id), container.workflowStore.readPassport(id)]); if (!job || !sessions || !passport) throw new Error(`Workflow job not found: ${id}`); const value = { job_id: id, phase: job.phase, current_agent: agentFor(job.phase), revision: job.revision, opus_iteration: job.opus_iteration, fable_calls: { pre_opus: `${job.fable_pre_opus_calls}/${passport.config.fable_pre_opus_cap}`, post_opus_iteration: `${job.fable_post_opus_iteration_calls}/${passport.config.fable_post_opus_per_iteration_cap}`, post_opus_total: job.fable_post_opus_calls, total: `${job.fable_total_calls}/${passport.config.fable_total_cap}` }, branch: job.branch, target_branch: job.target_branch, commit: job.current_commit, last_verdict: job.last_verdict, blocker: job.blocker, next_action: job.next_action, session_modes: sessions.modes, rotation_history: sessions.rotation_history, usage: sessions.usage }; if (container.context.json) print(container, value); else console.log([`Workflow ${id}: ${job.phase}`, `Revision ${job.revision}, implementation iteration ${job.opus_iteration}`, `Fable calls: ${value.fable_calls.pre_opus} pre-Opus; ${value.fable_calls.post_opus_iteration} this review; ${value.fable_calls.total} total`, `Context: Codex ${sessions.modes.codex}; Opus ${sessions.modes.opus}`, job.blocker ? `Blocked: ${job.blocker}` : `Next: ${job.next_action}`].join('\n')); });
  workflow.command('pause <job-id>').description('Pause a workflow').action(async (id: string) => { print(container, await container.workflowEngine.pause(id)); });
  workflow.command('resume <job-id>').description('Resume and run a workflow in the foreground').option('--approve-stop', 'Explicitly approve continuing after STOP').option('--retry-invocation', 'Explicitly retry an interrupted call with no durable result').requiredOption('--reason <reason>', 'Audit reason for resuming').action(async (id: string, options: { approveStop?: boolean; retryInvocation?: boolean; reason: string }) => { const result = await container.workflowEngine.resume(id, { approve_stop: options.approveStop, retry_invocation: options.retryInvocation, reason: options.reason }); print(container, result); if (result.phase === 'failed') process.exitCode = 1; });
  workflow.command('session-rotate <job-id> <role>').description('Rotate a codex, fable, or opus session').option('--reason <reason>', 'Audit reason', 'manual rotation').action(async (id: string, role: string, options: { reason: string }) => { if (!['codex', 'fable', 'opus'].includes(role)) throw new Error('Role must be codex, fable, or opus'); await container.workflowEngine.rotateSession(id, role as 'codex' | 'fable' | 'opus', options.reason); print(container, { job_id: id, role, rotated: true }); });
  workflow.command('cancel <job-id>').description('Cancel a workflow').action(async (id: string) => { print(container, await container.workflowEngine.cancel(id)); });
  workflow.command('logs <job-id>').description('Show durable workflow events').option('--raw', 'Show raw event data').action(async (id: string, options: { raw?: boolean }) => { const events = await container.workflowStore.readEvents(id); if (container.context.json || options.raw) console.log(JSON.stringify(events, null, 2)); else for (const event of events) console.log(`${event.timestamp} ${event.type}${event.type === 'phase_changed' ? `: ${(event.data as { from?: string }).from} -> ${(event.data as { to?: string }).to}` : ''}`); });
  workflow.command('artifacts <job-id>').description('List canonical workflow artifacts').action(async (id: string) => { const passport = await container.workflowStore.readPassport(id); if (!passport) throw new Error(`Workflow job not found: ${id}`); const root = path.join(container.context.projectRoot, '.orchestry', 'workflows', id, 'artifacts'); const artifacts = passport.artifacts.map((item) => ({ ...item, path: path.join(root, item.filename) })); if (container.context.json) print(container, artifacts); else for (const item of artifacts) console.log(`r${item.revision} i${item.iteration} ${item.phase} ${item.role}: ${item.filename}`); });
  workflow.command('doctor').description('Check native workflow CLIs and readiness').action(async () => { const { detectWorkflowCapabilities } = await import('../../infrastructure/workflow/native-adapters.js'); const capabilities = await detectWorkflowCapabilities(); const latest = (await container.workflowStore.listJobs())[0]; const passport = latest ? await container.workflowStore.readPassport(latest.job_id) : null; const meaningfulChecks = (passport?.required_checks.length ?? 0) > 0; const nodeCompatible = Number(process.versions.node.split('.')[0]) >= 20; const git = await gitVersion(); const unsupported = [...capabilities.codex.unsupported_options, ...capabilities.claude.unsupported_options]; const blocked = !nodeCompatible || git === 'unavailable' || !capabilities.codex.available || !capabilities.claude.available || unsupported.length > 0; print(container, { node: { version: process.version, compatible: nodeCompatible }, git, codex: capabilities.codex, claude: capabilities.claude, configured_models: { codex: container.config.workflow?.profiles?.codex?.model ?? 'codex', fable: container.config.workflow?.profiles?.fable?.model ?? 'fable', opus: container.config.workflow?.profiles?.opus?.model ?? 'opus' }, model_availability: 'Configured model names are validated by each CLI at invocation; help output does not provide a portable model catalog.', session_resume: { codex: capabilities.codex.native_resume ? 'native_resume' : capabilities.codex.advertised_native_resume ? 'passport_handoff_unverified' : 'passport_handoff', opus: capabilities.claude.native_resume ? 'native_resume' : capabilities.claude.advertised_native_resume ? 'passport_handoff_unverified' : 'passport_handoff' }, native_resume_opt_in: 'Set ORCHESTRY_ENABLE_NATIVE_RESUME=1 only after empirically verifying the installed CLI continuation behavior.', configuration: path.join(container.context.projectRoot, '.orchestry', 'config.yml'), dangerous_execution: container.config.execution.security.allow_permission_bypass && process.env.ORCHESTRY_ALLOW_DANGEROUS_EXECUTION === '1' ? 'enabled' : 'disabled', meaningful_verification: meaningfulChecks, readiness: blocked ? 'blocked' : meaningfulChecks ? 'ready' : 'degraded' }); });
}

function print(container: Container, value: unknown): void { console.log(JSON.stringify(value, null, container.context.json ? 2 : 2)); }
function agentFor(phase: string): string | null { if (phase.startsWith('codex')) return 'codex'; if (phase.startsWith('fable')) return 'fable'; if (phase === 'opus_execution') return 'opus'; return null; }
async function gitVersion(): Promise<string> { try { return (await promisify(execFile)('git', ['--version'])).stdout.trim(); } catch { return 'unavailable'; } }
