import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { GovernanceStoreV3 } from '../../../src/infrastructure/governance/governance-store-v3.js';
import type { GovernanceRecordV3 } from '../../../src/domain/governance/contracts-v3.js';

let root:string; let stateRoot:string; let store:GovernanceStoreV3;
const now='2026-08-11T10:00:00.000Z';
const snapshot={schema_version:3,kind:'binding_snapshot',governance_id:'gov_1',record_id:'bindings',bindings:[{binding_id:'planner',role:'planner',principal_id:'agent_1',adapter:'codex',model:'gpt'}],created_at:now} as const;
beforeEach(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'orch-governance-'));stateRoot=await fs.mkdtemp(path.join(os.tmpdir(),'orch-governance-key-'));const key=path.join(stateRoot,'controller.key');await fs.writeFile(key,Buffer.alloc(32,7),{mode:0o600});store=new GovernanceStoreV3(root,key)});
afterEach(async()=>{await Promise.all([fs.rm(root,{recursive:true,force:true}),fs.rm(stateRoot,{recursive:true,force:true})])});
describe('GovernanceStoreV3',()=>{
  it('writes immutable idempotent hashed records with restrictive permissions',async()=>{const first=await store.put(snapshot);expect((await store.put(snapshot)).record_hash).toBe(first.record_hash);const file=path.join(root,'.orchestry','governance','v3','gov_1','records','binding_snapshot','bindings.json');expect((await fs.stat(file)).mode&0o777).toBe(0o600);expect((await store.read('gov_1','binding_snapshot','bindings'))?.record_hash).toBe(first.record_hash)});
  it('rejects conflicting overwrite and stale references',async()=>{const first=await store.put(snapshot);await expect(store.put({...snapshot,created_at:'2026-08-11T10:00:01.000Z'})).rejects.toThrow('Conflicting');const plan={schema_version:3,kind:'decomposition_plan',governance_id:'gov_1',record_id:'plan',binding_snapshot:{kind:'binding_snapshot',record_id:'bindings',record_hash:'f'.repeat(64)},objective:'build',base_commit:'a'.repeat(40),target_branch:'main',units:[{unit_id:'a',objective:'A',depends_on:[],owned_path_prefixes:['src/a'],acceptance_criteria:['ok'],required_check_ids:[]}],integration_check_ids:[],created_by_binding_id:'planner',created_at:now} as const;expect(first.record_hash).not.toBe(plan.binding_snapshot.record_hash);await expect(store.put(plan)).rejects.toThrow('stale governance reference')});
  it('detects tampering on read',async()=>{await store.put(snapshot);const file=path.join(root,'.orchestry','governance','v3','gov_1','records','binding_snapshot','bindings.json');const value=JSON.parse(await fs.readFile(file,'utf8'));value.record.created_at='2026-08-11T10:00:01.000Z';await fs.writeFile(file,JSON.stringify(value));await expect(store.read('gov_1','binding_snapshot','bindings')).rejects.toThrow('integrity')});
  it('rejects a forged record even when its unkeyed hash is recomputed',async()=>{await store.put(snapshot);const file=path.join(root,'.orchestry','governance','v3','gov_1','records','binding_snapshot','bindings.json');const value=JSON.parse(await fs.readFile(file,'utf8'));value.record.created_at='2026-08-11T10:00:01.000Z';value.record_hash=(await import('node:crypto')).createHash('sha256').update(canonical(value.record)).digest('hex');await fs.writeFile(file,JSON.stringify(value));await expect(store.read('gov_1','binding_snapshot','bindings')).rejects.toThrow('integrity')});
  it('requires an external strict 0600 controller key',async()=>{const inside=path.join(root,'key');await fs.writeFile(inside,Buffer.alloc(32),{mode:0o600});expect(()=>new GovernanceStoreV3(root,inside)).toThrow('outside');const loose=path.join(stateRoot,'loose.key');await fs.writeFile(loose,Buffer.alloc(32),{mode:0o644});await expect(new GovernanceStoreV3(root,loose).put(snapshot)).rejects.toThrow('0600')});
  it('allows exactly one winner for concurrent conflicting writes',async()=>{const competing={...snapshot,created_at:'2026-08-11T10:00:01.000Z'};const results=await Promise.allSettled([store.put(snapshot),store.put(competing)]);expect(results.filter((result)=>result.status==='fulfilled')).toHaveLength(1);expect(results.filter((result)=>result.status==='rejected')).toHaveLength(1);const stored=await store.read('gov_1','binding_snapshot','bindings');expect([snapshot.created_at,competing.created_at]).toContain((stored!.record as typeof snapshot).created_at)});
  it('rejects direct writes of authority-owned records',async()=>{const ref={kind:'binding_snapshot' as const,record_id:'bindings',record_hash:'a'.repeat(64)};const check={schema_version:3,kind:'check_binding',governance_id:'gov_1',record_id:'check',binding_snapshot:ref,subject:{kind:'candidate',id:'candidate',commit:'b'.repeat(40)},check_id:'test',command:'npm test',status:'passed',output_hash:'c'.repeat(64),executed_by_binding_id:'checker',provenance:{command_source:'trusted',execution_environment:'sandboxed'},started_at:now,completed_at:now} as GovernanceRecordV3;const approval={schema_version:3,kind:'human_approval',governance_id:'gov_1',record_id:'approval',subject:{kind:'candidate_evidence',record_id:'candidate',record_hash:'d'.repeat(64)},approved_by:'forged',reason:'forged',approved_at:now} as GovernanceRecordV3;await expect(store.put(check as never)).rejects.toThrow('trusted governance authority');await expect(store.put(approval as never)).rejects.toThrow('trusted governance authority')});
});

function canonical(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;const o=value as Record<string,unknown>;return`{${Object.keys(o).sort().map((key)=>`${JSON.stringify(key)}:${canonical(o[key])}`).join(',')}}`;}
