import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { WorkflowArtifactStore } from '../../../src/infrastructure/workflow/artifact-store.js';
import type { WorkflowJobV2, WorkflowPassportV2, WorkflowSessionsV2 } from '../../../src/domain/workflow/state.js';
import { validateCodexDecision } from '../../../src/domain/workflow/contracts.js';
import { clearEnsuredDirs, closeAllAppendHandles } from '../../../src/infrastructure/storage/fs-utils.js';

let root: string; let store: WorkflowArtifactStore; const now = '2026-08-04T00:00:00.000Z';
beforeEach(async () => { root = await fs.mkdtemp(path.join(os.tmpdir(), 'workflow-store-v2-')); store = new WorkflowArtifactStore(root); await create(); });
afterEach(async () => { closeAllAppendHandles(); clearEnsuredDirs(); await fs.rm(root, { recursive: true, force: true }); });
async function create() { const profiles = { fable: { model: 'fable', effort: 'low', max_turns: 1, timeout_ms: 1000, permission_mode: 'read_only' }, opus: { model: 'opus', effort: 'high', max_turns: 50, timeout_ms: 1000, permission_mode: 'worktree' }, codex: { model: 'codex', effort: 'medium', max_turns: 1, timeout_ms: 1000, permission_mode: 'read_only' } } as const; const job: WorkflowJobV2 = { schema_version: 2, job_id: 'wf_safe', mode: 'adaptive', phase: 'codex_pre_opus', resume_phase: null, revision: 1, artifact_revision: 0, latest_artifact_hash: null, opus_iteration: 1, fix_cycles: 0, fable_calls: 0, consultation_status: 'unused', consultation_origin: null, branch: null, worktree: null, target_branch: null, base_commit: null, current_commit: null, reviewed_diff_hash: null, accepted_brief_hash: null, last_action: null, blocker: null, next_action: 'decide', current_operation: null, created_at: now, updated_at: now }; const passport: WorkflowPassportV2 = { schema_version: 2, passport_revision: 1, job_id: 'wf_safe', mode: 'adaptive', current_revision: 1, objective: 'build', current_phase: 'codex_pre_opus', accepted_brief_hash: null, latest_implementation_brief: null, hard_constraints: [], acceptance_criteria: [], decisions: [], allowed_file_scope: [], required_checks: ['npm test'], current_blockers: [], next_action: 'decide', artifacts: [], active_worktree: null, target_branch: null, base_commit: null, current_commit: null, session_references: { codex: null, opus: null }, session_modes: { codex: 'none', opus: 'none' }, rotation_history: [], config: { fable_total_cap: 1, max_input_bytes: 1000, max_output_bytes: 1000, passport_max_bytes: 64000, profiles } }; const empty = { calls: 0, input_chars: 0, output_chars: 0, input_tokens: 0, output_tokens: 0, estimated_tokens: 0, cache_read: 0, cache_write: 0, duration_ms: 0, failed_calls: 0, resumes: 0, compactions: 0 }; const sessions: WorkflowSessionsV2 = { schema_version: 2, job_id: 'wf_safe', codex_thread_id: null, opus_session_id: null, opus_brief_hash: null, modes: { codex: 'none', opus: 'none' }, rotation_history: [], recorded_invocations: [], usage: { codex: { ...empty }, fable: { ...empty }, opus: { ...empty } }, updated_at: now }; await store.createJob(job, passport, sessions); }

describe('WorkflowArtifactStore v2', () => {
  it('writes immutable, hashed, securely-permissioned artifacts', async () => { const decision = { schema_version: 2, job_id: 'wf_safe', action: 'DISPATCH_OPUS', summary: 'go', implementation_brief: 'x'.repeat(500), required_changes: [], risk_level: 'low', fable_query: null, reviewed_commit: null }; const stored = await store.writeArtifact({ job_id: 'wf_safe', name: 'codex_decision', phase: 'codex_pre_opus', revision: 1, invocation_id: 'inv_1', producing_role: 'codex', parent_artifact_hash: null, payload: decision, validate: (value) => validateCodexDecision(value, 'pre_opus'), timestamp: now }); const file = path.join(root, '.orchestry', 'workflows', 'wf_safe', 'artifacts', stored.metadata.filename); expect((await fs.stat(file)).mode & 0o777).toBe(0o600); expect(stored.metadata.artifact_hash).toMatch(/^[a-f0-9]{64}$/); await expect(store.writeArtifact({ job_id: 'wf_safe', name: 'codex_decision', phase: 'codex_pre_opus', revision: 1, invocation_id: 'inv_2', producing_role: 'codex', parent_artifact_hash: stored.metadata.artifact_hash, payload: decision, validate: (value) => validateCodexDecision(value, 'pre_opus') })).rejects.toThrow('Stale artifact revision'); });
  it('rejects traversal and malformed nested passport fields', async () => { await expect(store.readJob('../escape')).rejects.toThrow('Invalid workflow job id'); const passport = await store.readPassport('wf_safe'); await expect(store.writePassport({ ...passport!, passport_revision: 2, artifacts: [{ filename: '../escape', hash: 'a'.repeat(64), phase: 'codex_pre_opus', revision: 1, iteration: 1, role: 'codex' }] })).rejects.toThrow('filename is invalid'); });
  it('redacts secrets in events', async () => { await store.appendEvent({ schema_version: 2, job_id: 'wf_safe', type: 'note', timestamp: now, data: { message: 'token=supersecretvalue', env: { HOME: '/tmp' } } }); expect((await store.readEvents('wf_safe'))[0]?.data).toEqual({ message: 'token=[REDACTED]' }); });
  it('loads legacy v1 state as blocked and non-resumable', async () => { const dir = path.join(root, '.orchestry', 'workflows', 'wf_safe'); const old = { schema_version: 1, job_id: 'wf_safe', phase: 'fable_plan', revision: 1, artifact_revision: 0, fable_total_calls: 2, opus_iteration: 1, fix_cycles: 0, created_at: now, updated_at: now }; await fs.writeFile(path.join(dir, 'job.json'), JSON.stringify(old)); expect(await store.readJob('wf_safe')).toMatchObject({ schema_version: 2, phase: 'blocked', blocker: expect.stringContaining('LEGACY_SCHEMA') }); });
});
