import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { WorkflowArtifactStore } from '../../../src/infrastructure/workflow/artifact-store.js';
import type { WorkflowJobV2, WorkflowPassportV2, WorkflowSessionsV2 } from '../../../src/domain/workflow/state.js';
import { validateCodexDecision } from '../../../src/domain/workflow/contracts.js';
import { clearEnsuredDirs, closeAllAppendHandles } from '../../../src/infrastructure/storage/fs-utils.js';

let root: string; let store: WorkflowArtifactStore; const now = '2026-08-04T00:00:00.000Z';
beforeEach(async () => { root = await fs.mkdtemp(path.join(os.tmpdir(), 'workflow-store-v2-')); store = new WorkflowArtifactStore(root); await create(); });
afterEach(async () => { closeAllAppendHandles(); clearEnsuredDirs(); await fs.rm(root, { recursive: true, force: true }); });
async function create() { const profiles = { fable: { model: 'fable', effort: 'low', max_turns: 1, timeout_ms: 1000, permission_mode: 'read_only' }, opus: { model: 'opus', effort: 'high', max_turns: 50, timeout_ms: 1000, permission_mode: 'worktree' }, codex: { model: 'codex', effort: 'medium', max_turns: 1, timeout_ms: 1000, permission_mode: 'read_only' } } as const; const job: WorkflowJobV2 = { schema_version: 2, job_id: 'wf_safe', mode: 'adaptive', phase: 'codex_pre_opus', resume_phase: null, revision: 1, artifact_revision: 0, latest_artifact_hash: null, opus_iteration: 1, fix_cycles: 0, fable_calls: 0, consultation_status: 'unused', consultation_origin: null, branch: null, worktree: null, target_branch: null, base_commit: null, current_commit: null, reviewed_diff_hash: null, accepted_brief_hash: null, last_action: null, blocker: null, next_action: 'decide', current_operation: null, created_at: now, updated_at: now }; const passport: WorkflowPassportV2 = { schema_version: 2, passport_revision: 1, job_id: 'wf_safe', mode: 'adaptive', current_revision: 1, objective: 'build', current_phase: 'codex_pre_opus', accepted_brief_hash: null, latest_implementation_brief: null, hard_constraints: [], acceptance_criteria: [], decisions: [], allowed_file_scope: [], required_checks: ['npm test'], current_blockers: [], next_action: 'decide', artifacts: [], active_worktree: null, target_branch: null, base_commit: null, current_commit: null, session_references: { codex: null, opus: null }, session_modes: { codex: 'none', opus: 'none' }, rotation_history: [], config: { fable_total_cap: 1, max_input_bytes: 1000, max_output_bytes: 1000, passport_max_bytes: 64000, profiles } }; const empty = { calls: 0, input_chars: 0, output_chars: 0, input_tokens: 0, output_tokens: 0, estimated_tokens: 0, cache_read: 0, cache_write: 0, duration_ms: 0, failed_calls: 0, resumes: 0, compactions: 0 }; const sessions: WorkflowSessionsV2 = { schema_version: 2, sessions_revision: 1, job_id: 'wf_safe', codex_thread_id: null, opus_session_id: null, opus_brief_hash: null, modes: { codex: 'none', opus: 'none' }, rotation_history: [], recorded_invocations: [], usage: { codex: { ...empty }, fable: { ...empty }, opus: { ...empty } }, updated_at: now }; await store.createJob(job, passport, sessions); }

describe('WorkflowArtifactStore v2', () => {
  it('writes immutable, hashed, securely-permissioned artifacts', async () => { const decision = { schema_version: 2, job_id: 'wf_safe', action: 'DISPATCH_OPUS', summary: 'go', implementation_brief: 'x'.repeat(500), required_changes: [], risk_level: 'low', fable_query: null, reviewed_commit: null, fable_advice_disposition: null, fable_error: null, fable_iteration_effect: null }; const stored = await store.writeArtifact({ job_id: 'wf_safe', name: 'codex_decision', phase: 'codex_pre_opus', revision: 1, invocation_id: 'inv_1', producing_role: 'codex', parent_artifact_hash: null, payload: decision, validate: (value) => validateCodexDecision(value, 'pre_opus'), timestamp: now }); const file = path.join(root, '.orchestry', 'workflows', 'wf_safe', 'artifacts', stored.metadata.filename); expect((await fs.stat(file)).mode & 0o777).toBe(0o600); expect(stored.metadata.artifact_hash).toMatch(/^[a-f0-9]{64}$/); await expect(store.writeArtifact({ job_id: 'wf_safe', name: 'codex_decision', phase: 'codex_pre_opus', revision: 1, invocation_id: 'inv_2', producing_role: 'codex', parent_artifact_hash: stored.metadata.artifact_hash, payload: decision, validate: (value) => validateCodexDecision(value, 'pre_opus') })).rejects.toThrow('Stale artifact revision'); });
  it('rejects traversal and malformed nested passport fields', async () => { await expect(store.readJob('../escape')).rejects.toThrow('Invalid workflow job id'); const passport = await store.readPassport('wf_safe'); await expect(store.writePassport({ ...passport!, passport_revision: 2, artifacts: [{ filename: '../escape', hash: 'a'.repeat(64), phase: 'codex_pre_opus', revision: 1, iteration: 1, role: 'codex' }] })).rejects.toThrow('filename is invalid'); });
  it('redacts secrets in events', async () => { await store.appendEvent({ schema_version: 2, job_id: 'wf_safe', type: 'note', timestamp: now, data: { message: 'token=supersecretvalue', env: { HOME: '/tmp' } } }); expect((await store.readEvents('wf_safe'))[0]?.data).toEqual({ message: 'token=[REDACTED]' }); });
  it('loads legacy v1 state as blocked and non-resumable', async () => { const dir = path.join(root, '.orchestry', 'workflows', 'wf_safe'); const old = { schema_version: 1, job_id: 'wf_safe', phase: 'fable_plan', revision: 1, artifact_revision: 0, fable_total_calls: 2, opus_iteration: 1, fix_cycles: 0, created_at: now, updated_at: now }; await fs.writeFile(path.join(dir, 'job.json'), JSON.stringify(old)); expect(await store.readJob('wf_safe')).toMatchObject({ schema_version: 2, phase: 'blocked', blocker: expect.stringContaining('LEGACY_SCHEMA') }); });
  it('recovers a standalone passport update from its journal', async () => { const passport = (await store.readPassport('wf_safe'))!; const updated = { ...passport, passport_revision: 2, next_action: 'recovered' }; const dir = path.join(root, '.orchestry', 'workflows', 'wf_safe'); await fs.writeFile(path.join(dir, 'passport.pending.json'), JSON.stringify({ passport: updated })); expect(await store.readPassport('wf_safe')).toMatchObject({ passport_revision: 2, next_action: 'recovered' }); expect(JSON.parse(await fs.readFile(path.join(dir, 'passports', 'passport-000002.json'), 'utf8'))).toMatchObject({ next_action: 'recovered' }); await expect(fs.access(path.join(dir, 'passport.pending.json'))).rejects.toThrow(); });
  it('increments workflow and passport revisions atomically on transition', async () => { const job = await store.commitTransition('wf_safe', 'opus_execution', {}, {}); const passport = await store.readPassport('wf_safe'); expect(job.revision).toBe(2); expect(passport).toMatchObject({ current_revision: 2, current_phase: 'opus_execution' }); });
  it('retains immutable session usage snapshots', async () => { const sessions = (await store.readSessions('wf_safe'))!; const updated = { ...sessions, sessions_revision: 2, recorded_invocations: ['inv_usage'], usage: { ...sessions.usage, codex: { ...sessions.usage.codex, calls: 1 } }, updated_at: new Date().toISOString() }; await store.writeSessions(updated); const dir = path.join(root, '.orchestry', 'workflows', 'wf_safe', 'sessions'); const snapshots = await fs.readdir(dir); expect(snapshots).toEqual(['sessions-000002.json']); expect(JSON.parse(await fs.readFile(path.join(dir, snapshots[0]!), 'utf8'))).toMatchObject({ sessions_revision: 2, recorded_invocations: ['inv_usage'], usage: { codex: { calls: 1 } } }); });
  it('rejects tampered invocation and effect receipts', async () => { const dir = path.join(root, '.orchestry', 'workflows', 'wf_safe'); const request = { task: 'safe' }; const result = { value: 'ok' }; await store.writeInvocationReceipt({ schema_version: 2, job_id: 'wf_safe', invocation_id: 'inv_tamper', phase: 'codex_pre_opus', role: 'codex', request_hash: 'a'.repeat(64), request, result_hash: 'b'.repeat(64), workflow_revision: 1, timestamp: now, result }); const invocationFile = path.join(dir, 'invocations', 'inv_tamper.json'); const invocation = JSON.parse(await fs.readFile(invocationFile, 'utf8')); await fs.writeFile(invocationFile, JSON.stringify({ ...invocation, result: { value: 'tampered' } })); await expect(store.readInvocationReceipt('wf_safe', 'inv_tamper')).rejects.toThrow('Invalid invocation receipt'); const effectRequest = { command: 'npm test' }; const effect = { schema_version: 2 as const, job_id: 'wf_safe', invocation_id: 'inv_effect', phase: 'codex_pre_opus' as const, kind: 'checks' as const, request_hash: 'a'.repeat(64), request: effectRequest, result_hash: 'b'.repeat(64), workflow_revision: 1, status: 'completed' as const, timestamp: now, result: { passed: true } }; await store.writeEffectReceipt(effect); const effectFile = path.join(dir, 'effects', 'inv_effect-checks-completed.json'); const persistedEffect = JSON.parse(await fs.readFile(effectFile, 'utf8')); await fs.writeFile(effectFile, JSON.stringify({ ...persistedEffect, result: { passed: false } })); await expect(store.readEffectReceipt('wf_safe', 'inv_effect', 'checks')).rejects.toThrow('Invalid workflow effect receipt'); });
  it('hashes the redacted persisted receipt content', async () => { const request = { task: 'safe', token: 'secret-value' }; const result = { value: 'ok', password: 'secret-value' }; await store.writeInvocationReceipt({ schema_version: 2, job_id: 'wf_safe', invocation_id: 'inv_redacted', phase: 'codex_pre_opus', role: 'codex', request_hash: 'a'.repeat(64), request, result_hash: 'b'.repeat(64), workflow_revision: 1, timestamp: now, result }); expect(await store.readInvocationReceipt('wf_safe', 'inv_redacted')).toMatchObject({ request: { task: 'safe' }, result: { value: 'ok' } }); });
  it('discards stale journals without rolling canonical state back', async () => { const dir = path.join(root, '.orchestry', 'workflows', 'wf_safe'); const passport = (await store.readPassport('wf_safe'))!; await store.writePassport({ ...passport, passport_revision: 2, next_action: 'newer' }); await fs.writeFile(path.join(dir, 'passport.pending.json'), JSON.stringify({ passport })); expect(await store.readPassport('wf_safe')).toMatchObject({ passport_revision: 2, next_action: 'newer' }); const sessions = (await store.readSessions('wf_safe'))!; await store.writeSessions({ ...sessions, sessions_revision: 2, updated_at: new Date().toISOString() }); await fs.writeFile(path.join(dir, 'sessions.pending.json'), JSON.stringify({ sessions })); expect(await store.readSessions('wf_safe')).toMatchObject({ sessions_revision: 2 }); });
});
