import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { ProcessManager } from '../../src/infrastructure/process/process-manager.js';
import { NativeCodexWorkflowAdapter, NativeFableWorkflowAdapter, NativeOpusWorkflowAdapter, detectWorkflowCapabilities } from '../../src/infrastructure/workflow/native-adapters.js';
import type { WorkflowPassportV1 } from '../../src/domain/workflow/state.js';

let root: string; let originalPath: string | undefined; let originalHome: string | undefined; let originalResumeOptIn: string | undefined;
beforeEach(async () => { root = await fs.mkdtemp(path.join(os.tmpdir(), 'orch-fake-exec-')); originalPath = process.env.PATH; originalHome = process.env.HOME; originalResumeOptIn = process.env.ORCHESTRY_ENABLE_NATIVE_RESUME; const bin = path.join(root, 'bin'); const home = path.join(root, 'home'); await fs.mkdir(bin); await fs.mkdir(path.join(home, '.orch-fake'), { recursive: true }); const fixture = path.resolve('test/fixtures/fake-agent-cli.mjs'); for (const name of ['claude', 'codex']) { const target = path.join(bin, name); await fs.copyFile(fixture, target); await fs.chmod(target, 0o755); } process.env.PATH = `${bin}:${originalPath ?? ''}`; process.env.HOME = home; process.env.ORCHESTRY_ENABLE_NATIVE_RESUME = '1'; });
afterEach(async () => { process.env.PATH = originalPath; process.env.HOME = originalHome; if (originalResumeOptIn === undefined) delete process.env.ORCHESTRY_ENABLE_NATIVE_RESUME; else process.env.ORCHESTRY_ENABLE_NATIVE_RESUME = originalResumeOptIn; await fs.rm(root, { recursive: true, force: true }); });

describe('workflow fake executables', () => {
  it('detects required capabilities without network access', async () => { const result = await detectWorkflowCapabilities(); expect(result.codex).toMatchObject({ available: true, unsupported_options: [], native_resume: true }); expect(result.claude).toMatchObject({ available: true, unsupported_options: [], native_resume: true }); const calls = await readCalls(); expect(calls).toHaveLength(4); });
  it('uses passport handoff unless advertised resume was empirically enabled', async () => { delete process.env.ORCHESTRY_ENABLE_NATIVE_RESUME; const result = await detectWorkflowCapabilities(); expect(result.codex).toMatchObject({ advertised_native_resume: true, native_resume: false }); expect(result.claude).toMatchObject({ advertised_native_resume: true, native_resume: false }); });

  it('uses exact role argv and stdin-only prompts', async () => {
    await scenario([{ text: JSON.stringify({ job_id: 'wf_1', objective: 'objective', constraints: [], allowed_file_scope: [], required_checks: ['test'] }) }, { text: 'final opus prompt' }, { text: JSON.stringify({ job_id: 'wf_1', status: 'completed', files_changed: [], commands_run: [], tests_reported: [], deviations: [], unresolved: [], summary: 'done' }) }]);
    const pm = new ProcessManager(); const passport = samplePassport();
    await new NativeCodexWorkflowAdapter(pm).brief(passport, null);
    await new NativeFableWorkflowAdapter(pm).finalPrompt(passport, { job_id: 'wf_1', revision: 1, assumptions: [], acceptance_criteria: [], implementation_steps: [], risks: [], questions_requiring_human: [] }, [], { workspace: root, model: 'fable-model', max_turns: 1, effort: 'low', timeout_ms: 1000, max_input_bytes: 10_000, max_output_bytes: 10_000 });
    await new NativeOpusWorkflowAdapter(pm).execute(passport, 'OPUS_SENTINEL', root, 'old-session', 'passport_handoff');
    const calls = (await readCalls()).filter((call) => !call.argv.includes('--help') && !call.argv.includes('--version'));
    expect(calls[0]?.argv).toEqual(['exec', '--json', '--sandbox', 'read-only', '--model', 'codex-model', '-c', 'model_reasoning_effort=medium', '-']);
    expect(calls[1]?.argv).toEqual(['--print', '--output-format', 'stream-json', '--max-turns', '1', '--verbose', '--model', 'fable-model', '--effort', 'low', '--bare', '--tools', '', '--disable-slash-commands', '--strict-mcp-config', '--mcp-config', '{"mcpServers":{}}', '--no-session-persistence']);
    expect(calls[2]?.argv).toEqual(['--print', '--output-format', 'stream-json', '--max-turns', '7', '--verbose', '--model', 'opus-model', '--effort', 'high']);
    expect(calls[2]?.stdin).toContain('OPUS_SENTINEL'); expect(calls.flatMap((call) => call.argv).join(' ')).not.toContain('OPUS_SENTINEL');
    for (const call of calls) expect(call.env).not.toContain('OPENAI_API_KEY');
  });

  it('fails closed on malformed native output', async () => { await scenario([{ text: 'not-json' }]); await expect(new NativeCodexWorkflowAdapter(new ProcessManager()).brief(samplePassport(), null)).rejects.toThrow('malformed JSON'); });
  it('terminates a timed-out child process', async () => { const passport = samplePassport(); passport.config.profiles.opus.timeout_ms = 25; await scenario([{ text: '{}', sleep_ms: 10_000 }]); const started = Date.now(); await expect(new NativeOpusWorkflowAdapter(new ProcessManager()).execute(passport, 'timeout', root, null, 'new')).rejects.toThrow('timed out'); expect(Date.now() - started).toBeLessThan(2_000); });
  it('uses verified native continuation syntax when advertised', async () => { await scenario([{ text: JSON.stringify({ job_id: 'wf_1', objective: 'objective', constraints: [], allowed_file_scope: [], required_checks: ['test'] }), session_id: 'same-codex' }, { text: JSON.stringify({ job_id: 'wf_1', status: 'completed', files_changed: [], commands_run: [], tests_reported: [], deviations: [], unresolved: [], summary: 'done' }), session_id: 'same-claude' }]); const passport = samplePassport(); const codex = await new NativeCodexWorkflowAdapter(new ProcessManager()).brief(passport, 'same-codex'); const opus = await new NativeOpusWorkflowAdapter(new ProcessManager()).execute(passport, 'continue', root, 'same-claude', 'native_resume'); const calls = (await readCalls()).filter((call) => !call.argv.includes('--help') && !call.argv.includes('--version')); expect(calls[0]?.argv.slice(0, 3)).toEqual(['exec', 'resume', 'same-codex']); expect(calls[1]?.argv).toEqual(expect.arrayContaining(['--resume', 'same-claude'])); expect(codex).toMatchObject({ resumed: true, session_mode: 'native_resume' }); expect(opus).toMatchObject({ resumed: true, session_mode: 'native_resume' }); });
  it('rotates through passport handoff when native continuation expires', async () => { await scenario([{ text: '', exit_code: 7, stderr: 'session expired' }, { text: JSON.stringify({ job_id: 'wf_1', objective: 'objective', constraints: [], allowed_file_scope: [], required_checks: ['test'] }), session_id: 'rotated-codex' }]); const result = await new NativeCodexWorkflowAdapter(new ProcessManager()).brief(samplePassport(), 'expired-codex'); const calls = (await readCalls()).filter((call) => !call.argv.includes('--help') && !call.argv.includes('--version')); expect(calls[0]?.argv.slice(0, 3)).toEqual(['exec', 'resume', 'expired-codex']); expect(calls[1]?.argv[0]).toBe('exec'); expect(calls[1]?.argv[1]).not.toBe('resume'); expect(result).toMatchObject({ session_id: 'rotated-codex', session_mode: 'passport_handoff', resume_failed: true }); });
  it('does not retry a resumed session that returns malformed output', async () => { await scenario([{ text: 'not-json' }, { text: '{}' }]); await expect(new NativeCodexWorkflowAdapter(new ProcessManager()).brief(samplePassport(), 'same-codex')).rejects.toThrow('malformed JSON'); const calls = (await readCalls()).filter((call) => !call.argv.includes('--help') && !call.argv.includes('--version')); expect(calls).toHaveLength(1); });
  it('does not retry an ambiguously timed-out Opus continuation', async () => { const passport = samplePassport(); passport.config.profiles.opus.timeout_ms = 250; await scenario([{ text: '{}', sleep_ms: 10_000 }, { text: '{}' }]); await expect(new NativeOpusWorkflowAdapter(new ProcessManager()).execute(passport, 'continue', root, 'same-claude', 'native_resume')).rejects.toThrow('timed out'); const calls = (await readCalls()).filter((call) => !call.argv.includes('--help') && !call.argv.includes('--version')); expect(calls).toHaveLength(1); });
  it('uses one passport fallback after an explicit expired Opus session error', async () => { await scenario([{ text: '', exit_code: 7, stderr: 'session expired' }, { text: JSON.stringify({ job_id: 'wf_1', status: 'completed', files_changed: [], commands_run: [], tests_reported: [], deviations: [], unresolved: [], summary: 'done' }), session_id: 'rotated-opus' }]); const result = await new NativeOpusWorkflowAdapter(new ProcessManager()).execute(samplePassport(), 'continue', root, 'expired-opus', 'native_resume'); const calls = (await readCalls()).filter((call) => !call.argv.includes('--help') && !call.argv.includes('--version')); expect(calls).toHaveLength(2); expect(calls[1]?.argv).not.toContain('--resume'); expect(calls[1]?.stdin).toContain('compact passport handoff'); expect(result).toMatchObject({ session_id: 'rotated-opus', session_mode: 'passport_handoff', resume_failed: true }); });
  it('includes compact passport context when resume is unavailable', async () => { const help = path.join(root, 'bin', 'claude'); await fs.writeFile(help, (await fs.readFile(help, 'utf8')).replace(' --resume', '')); await scenario([{ text: JSON.stringify({ job_id: 'wf_1', status: 'completed', files_changed: [], commands_run: [], tests_reported: [], deviations: [], unresolved: [], summary: 'done' }) }]); const result = await new NativeOpusWorkflowAdapter(new ProcessManager()).execute(samplePassport(), 'continue', root, 'old-claude', 'native_resume'); const calls = (await readCalls()).filter((call) => !call.argv.includes('--help') && !call.argv.includes('--version')); expect(calls[0]?.stdin).toContain('compact passport handoff'); expect(calls[0]?.stdin).toContain('hard_constraints'); expect(result).toMatchObject({ session_mode: 'passport_handoff', resume_failed: true }); });
});

async function scenario(responses: unknown[]) { await fs.writeFile(path.join(root, 'home', '.orch-fake', 'scenario.json'), JSON.stringify({ responses })); }
async function readCalls(): Promise<Array<{ command: string; argv: string[]; cwd: string; stdin: string; env: string[] }>> { const file = path.join(root, 'home', '.orch-fake', 'calls.jsonl'); const text = await fs.readFile(file, 'utf8'); return text.trim().split('\n').filter(Boolean).map((line) => JSON.parse(line)); }
function samplePassport(): WorkflowPassportV1 { const profiles = { fable: { model: 'fable-model', effort: 'low', max_turns: 1, timeout_ms: 1000, permission_mode: 'read_only' }, opus: { model: 'opus-model', effort: 'high', max_turns: 7, timeout_ms: 1000, permission_mode: 'worktree' }, codex: { model: 'codex-model', effort: 'medium', max_turns: 1, timeout_ms: 1000, permission_mode: 'read_only' } } as const; return { schema_version: 1, passport_revision: 1, job_id: 'wf_1', current_revision: 1, objective: 'objective', current_phase: 'codex_brief', approved_plan_hash: 'a'.repeat(64), latest_accepted_plan: null, hard_constraints: ['stay safe'], acceptance_criteria: [], mandatory_amendments: [], decisions: [], allowed_file_scope: [], required_checks: ['test'], current_blockers: [], next_action: 'next', artifacts: [], active_worktree: root, target_branch: 'main', base_commit: 'a'.repeat(40), current_commit: null, session_references: { codex: null, fable: null, opus: null }, session_modes: { codex: 'none', fable: 'none', opus: 'none' }, rotation_history: [], config: { fable_pre_opus_cap: 2, fable_post_opus_per_iteration_cap: 1, fable_total_cap: 5, max_input_bytes: 10_000, max_output_bytes: 10_000, passport_max_bytes: 64_000, post_review: 'always', profiles } }; }
