import { PassThrough } from 'node:stream';
import { EventEmitter } from 'node:events';
import { describe, expect, it } from 'vitest';
import { NativeFableWorkflowAdapter, NativeOpenCodeWorkflowAdapter, NativeOpusWorkflowAdapter } from '../../src/infrastructure/workflow/native-adapters.js';
import type { ICommandRunner } from '../../src/infrastructure/process/command-runner.js';
import type { IProcessManager, SpawnResult } from '../../src/infrastructure/process/process-manager.js';
import type { WorkflowPassportV2 } from '../../src/domain/workflow/state.js';

describe('native workflow process boundaries v2', () => {
  it('keeps prompts on stdin and separates optional Fable from Opus profiles', async () => { const pm = new FakeProcessManager(); const runner = fakeRunner(pm); const passport = samplePassport(); pm.nextResult = JSON.stringify({ schema_version: 1, consultation_id: 'consult_1', answer: 'A', alternatives: [], uncertainties: [] }); await new NativeFableWorkflowAdapter(pm, runner).consult('wf_1', 'consult_1', { purpose: 'COMPARE_BOUNDED_OPTIONS', question: 'A or B?', verification_method: 'tests', fallback_if_skipped: { action: 'DISPATCH_OPUS', instructions: 'A' } }, { workspace: '/tmp/empty', model: 'fable-model', max_turns: 1, effort: 'low', timeout_ms: 1000, max_input_bytes: 10_000, max_output_bytes: 10_000 }); pm.nextResult = JSON.stringify({ job_id: 'wf_1', status: 'completed', files_changed: [], commands_run: [], tests_reported: [], deviations: [], unresolved: [], summary: 'done' }); await new NativeOpusWorkflowAdapter(pm, runner).execute(passport, 'secret prompt', '/tmp/worktree', null, 'new'); expect(pm.calls[0]?.args).toEqual(expect.arrayContaining(['--model', 'fable-model', '--effort', 'low', '--max-turns', '1', '--tools', ''])); expect(pm.calls[1]?.args).toEqual(expect.arrayContaining(['--model', 'opus-model', '--effort', 'high', '--max-turns', '17'])); expect(pm.calls.flatMap((call) => call.args).join(' ')).not.toContain('secret prompt'); expect(pm.calls[1]?.stdin).toContain('secret prompt'); });
  it('runs OpenCode with an explicit provider model and stdin-only prompt', async () => { const pm = new FakeProcessManager(); const passport = samplePassport(); passport.config.profiles.opus.model = 'ollama/qwen-coder'; pm.nextResult = JSON.stringify({ job_id: 'wf_1', status: 'completed', files_changed: [], commands_run: [], tests_reported: [], deviations: [], unresolved: [], summary: 'done' }); const result = await new NativeOpenCodeWorkflowAdapter(pm, fakeRunner(pm)).execute(passport, 'OPENCODE_SECRET', '/tmp/worktree', null, 'new'); expect(result.value.status).toBe('completed'); expect(pm.calls[0]?.args).toEqual(['run', '--format', 'json', '--pure', '--model', 'ollama/qwen-coder']); expect(pm.calls[0]?.args.join(' ')).not.toContain('OPENCODE_SECRET'); expect(pm.calls[0]?.stdin).toContain('OPENCODE_SECRET'); });
});
class FakeProcessManager implements IProcessManager { calls: Array<{ command: string; args: string[]; stdin: string }> = []; nextResult = ''; isAlive() { return false; } kill() {} async killWithGrace() {} spawn(command: string, args: string[]): SpawnResult { const child = new EventEmitter() as SpawnResult['process']; const stdin = new PassThrough(); const stdout = new PassThrough(); const stderr = new PassThrough(); Object.assign(child, { stdin, stdout, stderr, pid: 42, kill: () => true, unref: () => child }); const call = { command, args, stdin: '' }; this.calls.push(call); stdin.on('data', (chunk) => { call.stdin += chunk.toString(); }); queueMicrotask(() => { stdout.end(command === 'opencode' ? `${JSON.stringify({ type: 'text', sessionID: 'fake', part: { text: this.nextResult } })}\n${JSON.stringify({ type: 'step_finish', sessionID: 'fake', part: { tokens: { input: 1, output: 1 } } })}\n` : `${JSON.stringify({ type: 'result', result: this.nextResult, session_id: 'fake', usage: {} })}\n`); child.emit('close', 0); }); return { process: child, pid: 42 }; } }
function fakeRunner(pm: FakeProcessManager): ICommandRunner { return { resolveExecutable: async (command) => ({ path: `/${command}`, realpath: `/${command}`, sha256: 'a'.repeat(64) }), start: () => { throw new Error('unused'); }, run: async (request) => { const executable = typeof request.executable === 'string' ? request.executable : request.executable.realpath; const call = { command: executable.replace(/^\//, ''), args: [...(request.args ?? [])], stdin: String(request.stdin ?? '') }; pm.calls.push(call); const payload = call.command === 'opencode' ? `${JSON.stringify({ type: 'text', sessionID: 'fake', part: { text: pm.nextResult } })}\n${JSON.stringify({ type: 'step_finish', sessionID: 'fake', part: { tokens: { input: 1, output: 1 } } })}\n` : `${JSON.stringify({ type: 'result', result: pm.nextResult, session_id: 'fake', usage: {} })}\n`; return { ok: true, stdout: payload, stderr: '', termination: 'exited', exitCode: 0 } as any; } }; }
function samplePassport(): WorkflowPassportV2 { const profiles = { fable: { model: 'fable-model', effort: 'low', max_turns: 1, timeout_ms: 1000, permission_mode: 'read_only' }, opus: { model: 'opus-model', effort: 'high', max_turns: 17, timeout_ms: 1000, permission_mode: 'worktree' }, codex: { model: 'codex-model', effort: 'medium', max_turns: 1, timeout_ms: 1000, permission_mode: 'read_only' } } as const; return { schema_version: 2, passport_revision: 1, job_id: 'wf_1', mode: 'adaptive', current_revision: 1, objective: 'test', current_phase: 'opus_execution', accepted_brief_hash: 'a'.repeat(64), latest_implementation_brief: null, hard_constraints: [], acceptance_criteria: ['ok'], decisions: [], allowed_file_scope: [], required_checks: ['npm test'], current_blockers: [], next_action: 'run', artifacts: [], active_worktree: '/tmp/worktree', target_branch: 'main', base_commit: 'a'.repeat(40), current_commit: null, session_references: { codex: null, opus: null }, session_modes: { codex: 'none', opus: 'none' }, rotation_history: [], config: { fable_total_cap: 1, max_input_bytes: 10_000, max_output_bytes: 10_000, passport_max_bytes: 64_000, profiles } }; }
