import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { NativeWorkflowGitGateway } from '../../src/infrastructure/workflow/native-adapters.js';

const exec = promisify(execFile); let root: string; let gateway: NativeWorkflowGitGateway;
beforeEach(async () => { root = await fs.mkdtemp(path.join(os.tmpdir(), 'orch-git-gateway-')); await exec('git', ['init', '-b', 'main'], { cwd: root }); await exec('git', ['config', 'user.email', 'test@example.invalid'], { cwd: root }); await exec('git', ['config', 'user.name', 'Test'], { cwd: root }); await fs.writeFile(path.join(root, 'file.txt'), 'base\n'); await exec('git', ['add', '.'], { cwd: root }); await exec('git', ['commit', '-m', 'base'], { cwd: root }); gateway = new NativeWorkflowGitGateway(root); });
afterEach(async () => { await fs.rm(root, { recursive: true, force: true }); });

describe('NativeWorkflowGitGateway', () => {
  it('isolates implementation in a dedicated worktree', async () => { const prepared = await gateway.prepare('wf_test'); expect(prepared.target_branch).toBe('main'); expect(prepared.worktree).not.toBe(root); await fs.writeFile(path.join(prepared.worktree, 'file.txt'), 'changed\n'); await exec('git', ['add', '.'], { cwd: prepared.worktree }); await exec('git', ['commit', '-m', 'change'], { cwd: prepared.worktree }); expect(await fs.readFile(path.join(root, 'file.txt'), 'utf8')).toBe('base\n'); expect((await gateway.inspect(prepared.branch, prepared.worktree)).files_changed).toEqual(['file.txt']); });
  it('reconciles an existing prepared worktree after controller restart', async () => { const first = await gateway.prepare('wf_restart'); const second = await gateway.prepare('wf_restart'); expect(second).toEqual(first); });
  it('rejects a stale workflow branch instead of adopting it', async () => { await exec('git', ['branch', 'orchestry/workflow/wf_stale'], { cwd: root }); await exec('git', ['switch', 'orchestry/workflow/wf_stale'], { cwd: root }); await fs.writeFile(path.join(root, 'stale.txt'), 'stale\n'); await exec('git', ['add', '.'], { cwd: root }); await exec('git', ['commit', '-m', 'stale'], { cwd: root }); await exec('git', ['switch', 'main'], { cwd: root }); await expect(gateway.prepare('wf_stale')).rejects.toThrow('does not match the expected base'); });
  it('rejects merge after target branch drift', async () => { const prepared = await gateway.prepare('wf_drift'); const reviewedCommit = (await exec('git', ['rev-parse', prepared.branch], { cwd: root })).stdout.trim(); await fs.writeFile(path.join(root, 'other.txt'), 'drift\n'); await exec('git', ['add', '.'], { cwd: root }); await exec('git', ['commit', '-m', 'drift'], { cwd: root }); await expect(gateway.merge(prepared.branch, reviewedCommit, prepared.target_branch, prepared.base_commit)).resolves.toMatchObject({ success: false, detail: 'Target branch changed since workflow start' }); });
  it('rejects merge when the workflow branch moves after review', async () => { const prepared = await gateway.prepare('wf_move'); const reviewedCommit = (await exec('git', ['rev-parse', prepared.branch], { cwd: root })).stdout.trim(); await fs.writeFile(path.join(prepared.worktree, 'file.txt'), 'changed\n'); await exec('git', ['add', '.'], { cwd: prepared.worktree }); await exec('git', ['commit', '-m', 'unreviewed'], { cwd: prepared.worktree }); await expect(gateway.merge(prepared.branch, reviewedCommit, prepared.target_branch, prepared.base_commit)).resolves.toMatchObject({ success: false, detail: 'Workflow branch changed after review' }); });
  it('reconciles only while the controller remains on the recorded target branch', async () => { const prepared = await gateway.prepare('wf_reconcile'); await fs.writeFile(path.join(prepared.worktree, 'file.txt'), 'changed\n'); await exec('git', ['add', '.'], { cwd: prepared.worktree }); await exec('git', ['commit', '-m', 'change'], { cwd: prepared.worktree }); const commit = (await exec('git', ['rev-parse', 'HEAD'], { cwd: prepared.worktree })).stdout.trim(); await exec('git', ['merge', '--no-ff', prepared.branch, '-m', 'merge'], { cwd: root }); expect(await gateway.isMerged(prepared.branch, commit, prepared.target_branch, prepared.base_commit)).toBe(true); await exec('git', ['switch', '-c', 'other'], { cwd: root }); expect(await gateway.isMerged(prepared.branch, commit, prepared.target_branch, prepared.base_commit)).toBe(false); });
  it('does not reconcile an external merge containing unreviewed content', async () => { const prepared = await gateway.prepare('wf_extra'); await fs.writeFile(path.join(prepared.worktree, 'file.txt'), 'reviewed\n'); await exec('git', ['add', '.'], { cwd: prepared.worktree }); await exec('git', ['commit', '-m', 'reviewed'], { cwd: prepared.worktree }); const commit = (await exec('git', ['rev-parse', 'HEAD'], { cwd: prepared.worktree })).stdout.trim(); await exec('git', ['merge', '--no-ff', '--no-commit', prepared.branch], { cwd: root }); await fs.writeFile(path.join(root, 'extra.txt'), 'unreviewed\n'); await exec('git', ['add', '.'], { cwd: root }); await exec('git', ['commit', '-m', 'merge with extra'], { cwd: root }); expect(await gateway.isMerged(prepared.branch, commit, prepared.target_branch, prepared.base_commit)).toBe(false); });
});
