import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { WorkflowEngine } from '../../src/application/workflow/engine.js';
import type { CodexDecisionEvidence, CodexRolePort, FableCallOptions, FableRolePort, GitEvidence, OpusRolePort, WorkflowGitPort } from '../../src/application/workflow/ports.js';
import type { CheckResults, CodexDecisionStage, CodexDecisionV2, FableAdviceV1, OpusResult } from '../../src/domain/workflow/contracts.js';
import type { WorkflowPassportV2 } from '../../src/domain/workflow/state.js';
import { WorkflowArtifactStore, hashCanonical } from '../../src/infrastructure/workflow/artifact-store.js';
import { clearEnsuredDirs, closeAllAppendHandles } from '../../src/infrastructure/storage/fs-utils.js';

let root: string; let store: WorkflowArtifactStore; let fakes: Fakes; let engine: WorkflowEngine; const CHECKS = ['npm test'];
beforeEach(async () => { root = await fs.mkdtemp(path.join(os.tmpdir(), 'workflow-v2-e2e-')); store = new WorkflowArtifactStore(root); fakes = new Fakes(root); engine = new WorkflowEngine(store, { codex: fakes, fable: fakes, opus: fakes, git: fakes }); });
afterEach(async () => { closeAllAppendHandles(); clearEnsuredDirs(); await fs.rm(root, { recursive: true, force: true }); });

describe('direct Codex-Opus workflow v2', () => {
  it('completes adaptive default with zero Fable calls and two Codex decisions', async () => { const id = await engine.start({ objective: 'direct change', required_checks: CHECKS }); const result = await engine.run(id); expect(result.phase).toBe('done'); expect(result.fable_calls).toBe(0); expect(fakes).toMatchObject({ codexCalls: 2, fableCalls: 0, opusCalls: 1, merges: 1 }); expect(fakes.sequence).toEqual(['codex:pre_opus', 'opus', 'codex:post_opus']); });
  it('direct mode mechanically skips a requested consultation and executes fallback', async () => { fakes.decisions = [consult('DISPATCH_OPUS'), accept()]; const id = await engine.start({ objective: 'direct', mode: 'direct', required_checks: CHECKS }); const result = await engine.run(id); expect(result.phase).toBe('done'); expect(fakes.fableCalls).toBe(0); expect(result.consultation_status).toBe('fallback_executed'); expect(fakes.opusPrompts[0]).toContain('safe fallback'); });
  it('adaptive mode honors a configured zero Fable cap', async () => { fakes.decisions = [consult('DISPATCH_OPUS'), accept()]; const id = await engine.start({ objective: 'zero cap', config: { fable_total_cap: 0 }, required_checks: CHECKS }); const result = await engine.run(id); expect(result.phase).toBe('done'); expect(fakes.fableCalls).toBe(0); expect(result.consultation_status).toBe('fallback_executed'); });
  it('denies high-risk consultation through the persisted safe fallback', async () => { fakes.decisions = [{ ...consult('DISPATCH_OPUS'), risk_level: 'high' }, accept()]; const id = await engine.start({ objective: 'high risk', required_checks: CHECKS }); const result = await engine.run(id); expect(result.phase).toBe('done'); expect(fakes.fableCalls).toBe(0); expect((await store.readArtifact(id, 'routing_decision'))?.payload).toMatchObject({ reason: 'risk_not_low', action: 'DISPATCH_OPUS' }); });
  it('runs one bounded adaptive consultation and returns advice to Codex before Opus', async () => { fakes.decisions = [consult('DISPATCH_OPUS'), dispatch('verified advice'), accept()]; const id = await engine.start({ objective: 'optional advice', required_checks: CHECKS }); expect((await engine.run(id)).phase).toBe('done'); expect(fakes.fableCalls).toBe(1); expect(fakes.sequence).toEqual(['codex:pre_opus', 'fable', 'codex:after_fable_pre', 'opus', 'codex:post_opus']); expect(fakes.codexEvidence[1]?.fable_advice?.answer).toBe('option A'); });
  it('uses fallback when optional Fable fails without blocking direct progress', async () => { fakes.decisions = [consult('DISPATCH_OPUS'), accept()]; fakes.failFable = true; const id = await engine.start({ objective: 'fallback', required_checks: CHECKS }); const result = await engine.run(id); expect(result.phase).toBe('done'); expect(fakes.fableCalls).toBe(1); expect(result.consultation_status).toBe('fallback_executed'); expect(fakes.opusPrompts[0]).toContain('safe fallback'); });
  it('resumes a persisted consultation fallback without a second Fable attempt', async () => { fakes.decisions = [consult('DISPATCH_OPUS'), accept()]; const id = await engine.start({ objective: 'fallback restart', required_checks: CHECKS }); expect((await engine.advance(id)).phase).toBe('fable_consultation'); const operation = { phase: 'fable_consultation' as const, invocation_id: 'inv_interrupted_fallback', started_at: new Date().toISOString(), retry_count: 0 }; expect(await store.reserveOperation(id, 'fable_consultation', operation)).toBe(true); await store.patchJob(id, { consultation_status: 'fallback_executed' }); const result = await engine.run(id); expect(result.phase).toBe('done'); expect(fakes.fableCalls).toBe(0); expect(fakes.opusPrompts[0]).toContain('safe fallback'); });
  it('replays a successful Fable receipt after restart without losing its advice', async () => { fakes.decisions = [consult('DISPATCH_OPUS'), dispatch('verified advice'), accept()]; const id = await engine.start({ objective: 'receipt restart', required_checks: CHECKS }); expect((await engine.advance(id)).phase).toBe('fable_consultation'); const operation = { phase: 'fable_consultation' as const, invocation_id: 'inv_fable_receipt', started_at: new Date().toISOString(), retry_count: 0 }; expect(await store.reserveOperation(id, 'fable_consultation', operation)).toBe(true); const job = (await store.readJob(id))!; const query = (await store.readArtifact<ReturnType<typeof queryValue>>(id, 'fable_request'))!.payload; const consultationId = `consult_${id}_${job.revision}`; const request = { consultation_id: consultationId, query }; const receiptResult = { value: { schema_version: 1, consultation_id: consultationId, answer: 'persisted advice', alternatives: [], uncertainties: [] } }; await store.writeInvocationReceipt({ schema_version: 2, job_id: id, invocation_id: operation.invocation_id, phase: 'fable_consultation', role: 'fable', request_hash: hashCanonical(request), request, result_hash: hashCanonical(receiptResult), workflow_revision: job.revision, timestamp: new Date().toISOString(), result: receiptResult }); await store.patchJob(id, { consultation_status: 'attempt_started', fable_calls: 1 }); const result = await engine.run(id); expect(result.phase).toBe('done'); expect(fakes.fableCalls).toBe(0); expect(fakes.codexEvidence[1]?.fable_advice?.answer).toBe('persisted advice'); });
  it('skips duplicate consultation after the workflow budget is consumed', async () => { fakes.decisions = [consult('DISPATCH_OPUS'), dispatch('after advice'), consult('CORRECT_OPUS'), accept()]; const id = await engine.start({ objective: 'one only', required_checks: CHECKS }); expect((await engine.run(id)).phase).toBe('done'); expect(fakes.fableCalls).toBe(1); expect(fakes.opusCalls).toBe(2); expect(fakes.opusPrompts[1]).toContain('safe fallback'); });
  it('sends Codex corrections directly to Opus', async () => { fakes.decisions = [dispatch(), correct('fix directly'), accept()]; const id = await engine.start({ objective: 'correct', required_checks: CHECKS }); const result = await engine.run(id); expect(result.phase).toBe('done'); expect(fakes.fableCalls).toBe(0); expect(fakes.opusPrompts).toEqual(['implement directly', 'fix directly']); expect(result.opus_iteration).toBe(2); });
  it('rejects ACCEPT before review evidence', async () => { fakes.decisions = [{ ...accept(), reviewed_commit: null }]; const id = await engine.start({ objective: 'bad accept', required_checks: CHECKS }); const result = await engine.run(id); expect(result.phase).toBe('failed'); expect(result.blocker).toContain('invalid during pre_opus'); expect(fakes.opusCalls).toBe(0); });
  it('pauses rather than merging without meaningful checks', async () => { const id = await engine.start({ objective: 'no checks', required_checks: ['true'] }); const result = await engine.run(id); expect(result.phase).toBe('blocked'); expect(fakes.merges).toBe(0); });
  it('restarts after every phase without duplicate calls or merge', async () => { const id = await engine.start({ objective: 'restart', required_checks: CHECKS }); let result = await store.readJob(id); for (let i = 0; i < 20 && result?.phase !== 'done'; i++) result = await new WorkflowEngine(new WorkflowArtifactStore(root), { codex: fakes, fable: fakes, opus: fakes, git: fakes }).advance(id); expect(result?.phase).toBe('done'); expect(result?.revision).toBe(6); expect(fakes).toMatchObject({ codexCalls: 2, opusCalls: 1, merges: 1, checkCalls: 3 }); });
  it('resumes an active phase after terminal restart', async () => { const id = await engine.start({ objective: 'active restart', required_checks: CHECKS }); expect((await engine.advance(id)).phase).toBe('opus_execution'); const result = await new WorkflowEngine(new WorkflowArtifactStore(root), { codex: fakes, fable: fakes, opus: fakes, git: fakes }).resume(id, { reason: 'terminal restarted' }); expect(result.phase).toBe('done'); expect(fakes).toMatchObject({ codexCalls: 2, opusCalls: 1, merges: 1 }); });
  it('rotates session and passport identity in one recoverable commit', async () => { const id = await engine.start({ objective: 'rotation', required_checks: CHECKS }); await engine.rotateSession(id, 'opus', 'expired'); const sessions = await store.readSessions(id); const passport = await store.readPassport(id); expect(sessions).toMatchObject({ sessions_revision: 2, opus_session_id: null, rotation_history: [{ role: 'opus', reason: 'expired' }] }); expect(passport).toMatchObject({ session_references: { opus: null }, rotation_history: [{ role: 'opus', reason: 'expired' }] }); });
  it('replays completed verification checks without executing them twice', async () => { const id = await reachVerification(); const job = (await store.readJob(id))!; const operation = { phase: 'verification' as const, invocation_id: 'inv_checks_completed', started_at: new Date().toISOString(), retry_count: 0 }; expect(await store.reserveOperation(id, 'verification', operation)).toBe(true); const request = { worktree: job.worktree!, commit: job.current_commit!, commands: CHECKS }; const resultValue = checkResult(job.worktree!, job.current_commit!); await store.writeEffectReceipt({ schema_version: 2, job_id: id, invocation_id: operation.invocation_id, phase: 'verification', kind: 'checks', request_hash: hashCanonical(request), request, result_hash: hashCanonical(resultValue), workflow_revision: job.revision, status: 'completed', timestamp: new Date().toISOString(), result: resultValue }); const result = await engine.run(id); expect(result.phase).toBe('done'); expect(fakes.checkCalls).toBe(2); });
  it('blocks rather than repeating an ambiguous interrupted check', async () => { const id = await reachVerification(); const job = (await store.readJob(id))!; const operation = { phase: 'verification' as const, invocation_id: 'inv_checks_started', started_at: new Date().toISOString(), retry_count: 0 }; expect(await store.reserveOperation(id, 'verification', operation)).toBe(true); const request = { worktree: job.worktree!, commit: job.current_commit!, commands: CHECKS }; await store.writeEffectReceipt({ schema_version: 2, job_id: id, invocation_id: operation.invocation_id, phase: 'verification', kind: 'checks', request_hash: hashCanonical(request), request, result_hash: null, workflow_revision: job.revision, status: 'started', timestamp: new Date().toISOString(), result: null }); const result = await engine.run(id); expect(result.phase).toBe('blocked'); expect(result.blocker).toContain('AMBIGUOUS_EFFECT'); expect(fakes.checkCalls).toBe(1); });
  it('blocks on a stale reviewed diff', async () => { fakes.staleDiff = true; const id = await engine.start({ objective: 'stale diff', required_checks: CHECKS }); expect((await engine.run(id)).phase).toBe('blocked'); expect(fakes.merges).toBe(0); });
  it('fails closed on stale branch commit', async () => { fakes.staleCommit = true; const id = await engine.start({ objective: 'stale commit', required_checks: CHECKS }); expect((await engine.run(id)).phase).toBe('failed'); expect(fakes.merges).toBe(0); });
  it('fails closed when checks move the reviewed branch', async () => { fakes.moveCommitDuringFinalChecks = true; const id = await engine.start({ objective: 'moving commit', required_checks: CHECKS }); expect((await engine.run(id)).phase).toBe('failed'); expect(fakes.merges).toBe(0); });
  it('does not reconcile an externally merged unreviewed branch tip', async () => { fakes.staleCommit = true; fakes.merged = true; const id = await engine.start({ objective: 'unreviewed merge', required_checks: CHECKS }); expect((await engine.run(id)).phase).toBe('failed'); expect(fakes.merges).toBe(0); });
  it('fails closed on merge failure', async () => { fakes.mergeFails = true; const id = await engine.start({ objective: 'merge fail', required_checks: CHECKS }); expect((await engine.run(id)).phase).toBe('failed'); expect(fakes.merges).toBe(1); });

  async function reachVerification() { const id = await engine.start({ objective: 'effect recovery', required_checks: CHECKS }); expect((await engine.advance(id)).phase).toBe('opus_execution'); expect((await engine.advance(id)).phase).toBe('codex_post_opus'); expect((await engine.advance(id)).phase).toBe('verification'); return id; }
});

class Fakes implements CodexRolePort, FableRolePort, OpusRolePort, WorkflowGitPort {
  decisions: CodexDecisionV2[] = [dispatch(), accept()]; failFable = false; checksPass = true; staleDiff = false; staleCommit = false; moveCommitDuringFinalChecks = false; merged = false; mergeFails = false; codexCalls = 0; fableCalls = 0; opusCalls = 0; merges = 0; checkCalls = 0; commitIndex = 1; current = 'abcdef1'; sequence: string[] = []; opusPrompts: string[] = []; codexEvidence: CodexDecisionEvidence[] = [];
  constructor(private root: string) {}
  async available() { return { available: true, detail: 'fake' }; }
  async decide(p: WorkflowPassportV2, stage: CodexDecisionStage, evidence: CodexDecisionEvidence) { this.codexCalls++; this.sequence.push(`codex:${stage}`); this.codexEvidence.push(evidence); const value = this.decisions.shift() ?? accept(); const fableOutcome = stage.startsWith('after_fable') ? { fable_advice_disposition: 'accepted' as const, fable_error: null, fable_iteration_effect: 'unchanged' as const } : {}; return { value: { ...value, ...fableOutcome, job_id: p.job_id, ...(value.reviewed_commit === 'CURRENT' ? { reviewed_commit: evidence.evidence?.commit ?? null } : {}) }, session_id: 'codex-thread' }; }
  async consult(_job: string, consultationId: string, _query: unknown, _options: FableCallOptions) { this.fableCalls++; this.sequence.push('fable'); if (this.failFable) throw new Error('fable unavailable'); return { value: { schema_version: 1, consultation_id: consultationId, answer: 'option A', alternatives: ['option B'], uncertainties: [] } as FableAdviceV1 }; }
  async prepare(id: string) { const worktree = path.join(this.root, 'worktree', id); await fs.mkdir(worktree, { recursive: true }); return { branch: `orchestry/workflow/${id}`, worktree, target_branch: 'main', base_commit: 'abcdef1' }; }
  async execute(p: WorkflowPassportV2, prompt: string) { this.opusCalls++; this.sequence.push('opus'); this.opusPrompts.push(prompt); this.current = `abcdef${++this.commitIndex}`; return { value: { job_id: p.job_id, status: 'completed', files_changed: ['src/x.ts'], commands_run: ['npm test'], tests_reported: ['pass'], deviations: [], unresolved: [], summary: 'done' } as OpusResult, session_id: 'opus-session' }; }
  async inspect(branch: string, worktree: string): Promise<GitEvidence> { const changed = this.staleDiff && this.sequence.at(-1) === 'codex:post_opus'; return { branch, worktree, commit: this.current, diff: changed ? 'changed' : 'diff', diff_hash: changed ? 'b'.repeat(64) : hashCanonical('diff'), files_changed: ['src/x.ts'], insertions: 1, deletions: 0, risk_signals: [] }; }
  async runChecks(worktree: string, commit: string, commands: string[]): Promise<CheckResults> { this.checkCalls++; if (this.moveCommitDuringFinalChecks && this.checkCalls === 3) this.current = '9999999'; return { job_id: path.basename(worktree), commit, passed: this.checksPass, checks: commands.map((command) => ({ command, passed: this.checksPass, output: 'ok' })) }; }
  async currentCommit() { return this.staleCommit ? 'fffffff' : this.current; }
  async isMerged() { return this.merged; }
  async merge() { this.merges++; return this.mergeFails ? { success: false, detail: 'conflict' } : { success: true, detail: 'merged' }; }
}

function outcome() { return { fable_advice_disposition: null, fable_error: null, fable_iteration_effect: null } as const; }
function dispatch(brief = 'implement directly'): CodexDecisionV2 { return { schema_version: 2, job_id: 'wf_placeholder', action: 'DISPATCH_OPUS', summary: 'dispatch', implementation_brief: brief, required_changes: [], risk_level: 'low', fable_query: null, reviewed_commit: null, ...outcome() }; }
function accept(): CodexDecisionV2 { return { schema_version: 2, job_id: 'wf_placeholder', action: 'ACCEPT', summary: 'accept', implementation_brief: null, required_changes: [], risk_level: 'low', fable_query: null, reviewed_commit: 'CURRENT', ...outcome() }; }
function correct(change: string): CodexDecisionV2 { return { schema_version: 2, job_id: 'wf_placeholder', action: 'CORRECT_OPUS', summary: 'correct', implementation_brief: null, required_changes: [change], risk_level: 'medium', fable_query: null, reviewed_commit: 'CURRENT', ...outcome() }; }
function consult(fallback: 'DISPATCH_OPUS' | 'CORRECT_OPUS'): CodexDecisionV2 { return { schema_version: 2, job_id: 'wf_placeholder', action: 'CONSULT_FABLE', summary: 'consult', implementation_brief: null, required_changes: [], risk_level: 'low', fable_query: { purpose: 'COMPARE_BOUNDED_OPTIONS', question: 'A or B?', verification_method: 'compare deterministic tests', fallback_if_skipped: { action: fallback, instructions: 'safe fallback' } }, reviewed_commit: fallback === 'CORRECT_OPUS' ? 'CURRENT' : null, ...outcome() }; }
function queryValue() { return { purpose: 'COMPARE_BOUNDED_OPTIONS' as const, question: 'A or B?', verification_method: 'compare deterministic tests', fallback_if_skipped: { action: 'DISPATCH_OPUS' as const, instructions: 'safe fallback' } }; }
function checkResult(worktree: string, commit: string): CheckResults { return { job_id: path.basename(worktree), commit, passed: true, checks: CHECKS.map((command) => ({ command, passed: true, output: 'persisted' })) }; }
